// @generated by scripts/extract_elrail_catenary.py — no editar a mano.
// Fuente: bloque Action5 05/30 de OpenGFX ogfxe_extra.nfo.
// NFO: assets/opengfx/opengfx-8.0/sprites/ogfxe_extra.nfo.
#![cfg_attr(rustfmt, rustfmt_skip)]

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CatenarySpriteGfx {
    pub width: f32,
    pub height: f32,
    pub x_offs: f32,
    pub y_offs: f32,
}

/// Índice Action5: wires 0..23, entradas 24..27, postes 28..35.
pub const CATENARY_ACTION5_GFX: [CatenarySpriteGfx; 36] = [
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -29.0, y_offs: -2.0 }, // slot 0
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -1.0, y_offs: -2.0 }, // slot 1
    CatenarySpriteGfx { width: 32.0, height: 1.0, x_offs: -1.0, y_offs: -2.0 }, // slot 2
    CatenarySpriteGfx { width: 1.0, height: 16.0, x_offs: 0.0, y_offs: -3.0 }, // slot 3
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -29.0, y_offs: -2.0 }, // slot 4
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -1.0, y_offs: 6.0 }, // slot 5
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -29.0, y_offs: 6.0 }, // slot 6
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -1.0, y_offs: -2.0 }, // slot 7
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -29.0, y_offs: -2.0 }, // slot 8
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -1.0, y_offs: -2.0 }, // slot 9
    CatenarySpriteGfx { width: 32.0, height: 1.0, x_offs: -1.0, y_offs: -2.0 }, // slot 10
    CatenarySpriteGfx { width: 1.0, height: 16.0, x_offs: 0.0, y_offs: -3.0 }, // slot 11
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -29.0, y_offs: -2.0 }, // slot 12
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -1.0, y_offs: 6.0 }, // slot 13
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -29.0, y_offs: 6.0 }, // slot 14
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -1.0, y_offs: -2.0 }, // slot 15
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -29.0, y_offs: -2.0 }, // slot 16
    CatenarySpriteGfx { width: 32.0, height: 16.0, x_offs: -1.0, y_offs: -2.0 }, // slot 17
    CatenarySpriteGfx { width: 32.0, height: 1.0, x_offs: -1.0, y_offs: -2.0 }, // slot 18
    CatenarySpriteGfx { width: 1.0, height: 16.0, x_offs: 0.0, y_offs: -3.0 }, // slot 19
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -29.0, y_offs: -2.0 }, // slot 20
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -1.0, y_offs: 6.0 }, // slot 21
    CatenarySpriteGfx { width: 32.0, height: 9.0, x_offs: -29.0, y_offs: 6.0 }, // slot 22
    CatenarySpriteGfx { width: 32.0, height: 24.0, x_offs: -1.0, y_offs: -2.0 }, // slot 23
    CatenarySpriteGfx { width: 16.0, height: 8.0, x_offs: -29.0, y_offs: 6.0 }, // slot 24
    CatenarySpriteGfx { width: 16.0, height: 8.0, x_offs: -1.0, y_offs: -2.0 }, // slot 25
    CatenarySpriteGfx { width: 16.0, height: 8.0, x_offs: -13.0, y_offs: -2.0 }, // slot 26
    CatenarySpriteGfx { width: 16.0, height: 8.0, x_offs: 15.0, y_offs: 6.0 }, // slot 27
    CatenarySpriteGfx { width: 8.0, height: 16.0, x_offs: -7.0, y_offs: -14.0 }, // slot 28
    CatenarySpriteGfx { width: 8.0, height: 18.0, x_offs: 0.0, y_offs: -17.0 }, // slot 29
    CatenarySpriteGfx { width: 8.0, height: 16.0, x_offs: 0.0, y_offs: -14.0 }, // slot 30
    CatenarySpriteGfx { width: 8.0, height: 18.0, x_offs: -7.0, y_offs: -17.0 }, // slot 31
    CatenarySpriteGfx { width: 2.0, height: 16.0, x_offs: 0.0, y_offs: -15.0 }, // slot 32
    CatenarySpriteGfx { width: 2.0, height: 18.0, x_offs: 0.0, y_offs: -16.0 }, // slot 33
    CatenarySpriteGfx { width: 8.0, height: 16.0, x_offs: 0.0, y_offs: -15.0 }, // slot 34
    CatenarySpriteGfx { width: 8.0, height: 16.0, x_offs: -7.0, y_offs: -15.0 }, // slot 35
];
