// @generated by scripts/gen_industry_draw_proc.py — no editar a mano.

/// Fila de `_draw_industry_spec1` / `_industry_anim_offs_toys`.
#[derive(Debug, Clone, Copy)]
pub struct DrawProcAnimRow {
    pub x: i32,
    pub image_1: u8,
    pub image_2: u8,
    pub image_3: u8,
}

/// Coordenada NFO `(dx, dy)` para child sprites.
#[derive(Debug, Clone, Copy)]
pub struct DrawProcCoord {
    pub x: u8,
    pub y: u8,
}

pub const SPR_IT_SUGAR_MINE_SIEVE: u32 = 4775;
pub const SPR_IT_SUGAR_MINE_CLOUDS: u32 = 4784;
pub const SPR_IT_SUGAR_MINE_PILE: u32 = 4780;
pub const SPR_IT_TOFFEE_QUARRY_TOFFEE: u32 = 4766;
pub const SPR_IT_TOFFEE_QUARRY_SHOVEL: u32 = 4767;
pub const SPR_IT_BUBBLE_GENERATOR_SPRING: u32 = 4746;
pub const SPR_IT_BUBBLE_GENERATOR_BUBBLE: u32 = 4747;
pub const SPR_IT_TOY_FACTORY_STAMP_HOLDER: u32 = 4717;
pub const SPR_IT_TOY_FACTORY_STAMP: u32 = 4718;
pub const SPR_IT_TOY_FACTORY_CLAY: u32 = 4719;
pub const SPR_IT_TOY_FACTORY_ROBOT: u32 = 4720;
pub const SPR_IT_POWER_PLANT_TRANSFORMERS: u32 = 2054;

/// `draw_proc` por fila `gfx * 4 + stage` (0 = ninguno).
pub const INDUSTRY_DRAW_PROC: [u8; 524] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

pub const DRAW_INDUSTRY_SPEC1: [DrawProcAnimRow; 96] = [
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 0,
        image_2: 1,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 0,
        image_2: 2,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 0,
        image_2: 3,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 0,
        image_2: 4,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 0,
        image_2: 5,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 0,
        image_2: 6,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 0,
        image_2: 1,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 0,
        image_2: 2,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 0,
        image_2: 3,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 0,
        image_2: 4,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 0,
        image_2: 5,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 0,
        image_2: 6,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 0,
        image_2: 1,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 0,
        image_2: 2,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 0,
        image_2: 3,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 1,
        image_2: 4,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 1,
        image_2: 5,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 1,
        image_2: 6,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 1,
        image_2: 1,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 1,
        image_2: 2,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 1,
        image_2: 3,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 1,
        image_2: 4,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 1,
        image_2: 5,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 1,
        image_2: 6,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 1,
        image_2: 1,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 1,
        image_2: 2,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 1,
        image_2: 3,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 1,
        image_2: 4,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 1,
        image_2: 5,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 1,
        image_2: 6,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 1,
        image_2: 1,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 2,
        image_2: 2,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 2,
        image_2: 3,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 2,
        image_2: 4,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 2,
        image_2: 5,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 2,
        image_2: 6,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 2,
        image_2: 1,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 2,
        image_2: 2,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 2,
        image_2: 3,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 2,
        image_2: 4,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 2,
        image_2: 5,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 2,
        image_2: 6,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 2,
        image_2: 1,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 2,
        image_2: 2,
        image_3: 3,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 2,
        image_2: 3,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 2,
        image_2: 4,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 2,
        image_2: 5,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 3,
        image_2: 6,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 3,
        image_2: 1,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 3,
        image_2: 2,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 3,
        image_2: 3,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 3,
        image_2: 4,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 3,
        image_2: 5,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 3,
        image_2: 6,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 3,
        image_2: 1,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 3,
        image_2: 2,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 3,
        image_2: 3,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 3,
        image_2: 4,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 3,
        image_2: 5,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 3,
        image_2: 6,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 3,
        image_2: 1,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 3,
        image_2: 2,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 3,
        image_2: 3,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 4,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 5,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 4,
        image_2: 6,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 4,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 6,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 8,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 12,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 10,
        image_1: 4,
        image_2: 0,
        image_3: 4,
    },
];

pub const DRAW_TILE_PROC1: [DrawProcCoord; 5] = [
    DrawProcCoord { x: 22, y: 73 },
    DrawProcCoord { x: 17, y: 70 },
    DrawProcCoord { x: 14, y: 69 },
    DrawProcCoord { x: 10, y: 66 },
    DrawProcCoord { x: 8, y: 41 },
];

pub const INDUSTRY_ANIM_OFFS_TOYS: [DrawProcAnimRow; 50] = [
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 50,
        image_1: 0,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 48,
        image_1: 1,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 46,
        image_1: 2,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 44,
        image_1: 3,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 42,
        image_1: 4,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 40,
        image_1: 5,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 38,
        image_1: 6,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 36,
        image_1: 7,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 34,
        image_1: 8,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 32,
        image_1: 9,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 30,
        image_1: 10,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 28,
        image_1: 11,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 26,
        image_1: 12,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 24,
        image_1: 13,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 22,
        image_1: 14,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 20,
        image_1: 15,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 18,
        image_1: 16,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 16,
        image_1: 17,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 6,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 8,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 11,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 14,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 17,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 20,
    },
    DrawProcAnimRow {
        x: 14,
        image_1: 18,
        image_2: 255,
        image_3: 24,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 29,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 24,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 20,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 17,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 14,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 11,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 8,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 6,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 4,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 2,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 0,
        image_3: 1,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 1,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 2,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 3,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 4,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 5,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 6,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 7,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 8,
        image_3: 0,
    },
    DrawProcAnimRow {
        x: -460,
        image_1: 255,
        image_2: 255,
        image_3: 0,
    },
];

pub const INDUSTRY_ANIM_OFFS_TOFFEE: [u8; 70] = [
    255, 0, 0, 0, 2, 4, 6, 8, 10, 9, 7, 5, 3, 1, 255, 0, 0, 0, 2, 4, 6, 8, 10, 9, 7, 5, 3, 1, 255,
    0, 0, 0, 2, 4, 6, 8, 10, 9, 7, 5, 3, 1, 255, 0, 0, 0, 2, 4, 6, 8, 10, 9, 7, 5, 3, 1, 255, 0, 0,
    0, 2, 4, 6, 8, 10, 9, 7, 5, 3, 1,
];

pub const INDUSTRY_ANIM_OFFS_BUBBLES: [u8; 40] = [
    68, 69, 71, 74, 77, 80, 83, 85, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 85, 84,
    83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68,
];

pub const COAL_PLANT_SPARKS: [DrawProcCoord; 6] = [
    DrawProcCoord { x: 11, y: 23 },
    DrawProcCoord { x: 11, y: 11 },
    DrawProcCoord { x: 14, y: 6 },
    DrawProcCoord { x: 13, y: 3 },
    DrawProcCoord { x: 18, y: 1 },
    DrawProcCoord { x: 15, y: 0 },
];

/// Sprites secundarios de draw_proc (precarga en `WorldAssets`).
pub const INDUSTRY_DRAW_PROC_SPRITE_IDS: [u32; 31] = [
    2055, 2056, 2057, 2058, 2059, 2060, 4717, 4718, 4719, 4720, 4746, 4747, 4766, 4767, 4775, 4776,
    4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791,
];
