// @generated by scripts/gen_rail_depot_gfx_data.py — no editar a mano.
// Fuente: OpenTTD src/table/track_land.h + OpenGFX NFO.
// Modo gráfico detectado: 8bpp.
#![cfg_attr(rustfmt, rustfmt_skip)]

#[derive(Debug, Clone, Copy)]
pub struct RailDepotLayerGfx {
    pub sprite_id: u32,
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    pub sx: i32,
    pub sy: i32,
    pub z: f32,
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub path: &'static str,
}

/// Índice: rail/electric, monorail, maglev; luego dirección NE/SE/SW/NW.
pub const RAIL_DEPOT_BUILD_LAYERS_BY_TYPE: [[&[RailDepotLayerGfx]; 4]; 3] = [
    [
        &[
            RailDepotLayerGfx { sprite_id: 1067, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 50.0, h: 38.0, x_offs: -47.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_ne.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1063, dx: 2.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 12.0, h: 8.0, x_offs: 15.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_se_1.png" },
            RailDepotLayerGfx { sprite_id: 1064, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.06, w: 50.0, h: 38.0, x_offs: -1.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_se_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1065, dx: 2.0, dy: 2.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 12.0, h: 8.0, x_offs: -25.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_sw_1.png" },
            RailDepotLayerGfx { sprite_id: 1066, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.06, w: 50.0, h: 38.0, x_offs: -47.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_sw_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1068, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 50.0, h: 38.0, x_offs: -1.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_nw.png" },
        ],
    ],
    [
        &[
            RailDepotLayerGfx { sprite_id: 1149, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 50.0, h: 38.0, x_offs: -47.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_mono_ne.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1145, dx: 2.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 12.0, h: 8.0, x_offs: 15.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_mono_se_1.png" },
            RailDepotLayerGfx { sprite_id: 1146, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.06, w: 50.0, h: 39.0, x_offs: -1.0, y_offs: -26.0, path: "assets/opengfx/tiles/rail_depot_mono_se_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1147, dx: 2.0, dy: 2.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 12.0, h: 8.0, x_offs: -25.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_mono_sw_1.png" },
            RailDepotLayerGfx { sprite_id: 1148, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.06, w: 50.0, h: 39.0, x_offs: -47.0, y_offs: -26.0, path: "assets/opengfx/tiles/rail_depot_mono_sw_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1150, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 50.0, h: 38.0, x_offs: -1.0, y_offs: -25.0, path: "assets/opengfx/tiles/rail_depot_mono_nw.png" },
        ],
    ],
    [
        &[
            RailDepotLayerGfx { sprite_id: 1231, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 50.0, h: 37.0, x_offs: -47.0, y_offs: -24.0, path: "assets/opengfx/tiles/rail_depot_maglev_ne.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1227, dx: 2.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 12.0, h: 8.0, x_offs: 15.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_maglev_se_1.png" },
            RailDepotLayerGfx { sprite_id: 1228, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.06, w: 50.0, h: 37.0, x_offs: -1.0, y_offs: -24.0, path: "assets/opengfx/tiles/rail_depot_maglev_se_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1229, dx: 2.0, dy: 2.0, dz: 0.0, sx: 13, sy: 1, z: 0.05, w: 12.0, h: 8.0, x_offs: -25.0, y_offs: 6.0, path: "assets/opengfx/tiles/rail_depot_maglev_sw_1.png" },
            RailDepotLayerGfx { sprite_id: 1230, dx: 2.0, dy: 13.0, dz: 0.0, sx: 13, sy: 1, z: 0.06, w: 50.0, h: 37.0, x_offs: -47.0, y_offs: -24.0, path: "assets/opengfx/tiles/rail_depot_maglev_sw_2.png" },
        ],
        &[
            RailDepotLayerGfx { sprite_id: 1232, dx: 13.0, dy: 2.0, dz: 0.0, sx: 1, sy: 13, z: 0.05, w: 50.0, h: 37.0, x_offs: -1.0, y_offs: -24.0, path: "assets/opengfx/tiles/rail_depot_maglev_nw.png" },
        ],
    ],
];
