// @generated by scripts/gen_road_stop_gfx_data.py — no editar a mano.
// Fuente: OpenTTD station_land.h (_station_display_datas_67..74, 168..171) + PNG/NFO.
// remap_x_adj: corrección fina por capa (±1 unidad TILE_SEQ ≈ 4 px); 0 = solo RemapCoords+NFO.
// Modo gráfico detectado: 8bpp (assets/opengfx/.graphics_mode o carpetas).


#[derive(Debug, Clone, Copy)]
pub struct RoadStopLayerGfx {
    /// ID global que recibe OpenTTD en `DrawTileSeq`.
    pub sprite_id: u32,
    /// Caja `TILE_SEQ_LINE(ex, ey, ez)`, no el tamaño del PNG.
    pub bounds: (i32, i32, i32),
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    pub z: f32,
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub remap_x_adj: f32,
    pub path: &'static str,
}

pub const BUS_STOP_BUILD_LAYERS: [[RoadStopLayerGfx; 3]; 4] = [
    [ // NE
        RoadStopLayerGfx { sprite_id: 2696, bounds: (11, 1, 10), dx: 2.0, dy: 0.0, dz: 0.0, z: 0.05, w: 21.0, h: 12.0, x_offs: -21.0, y_offs: -1.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_ne_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2700, bounds: (3, 16, 10), dx: 13.0, dy: 0.0, dz: 0.0, z: 0.06, w: 26.0, h: 22.0, x_offs: -1.0, y_offs: -13.0, remap_x_adj: 7.0, path: "assets/opengfx/tiles/bus_stop_ne_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2704, bounds: (13, 3, 10), dx: 0.0, dy: 13.0, dz: 0.0, z: 0.07, w: 26.0, h: 23.0, x_offs: -22.0, y_offs: -9.0, remap_x_adj: -13.0, path: "assets/opengfx/tiles/bus_stop_ne_build_c.png" },
    ],
    [ // SE
        RoadStopLayerGfx { sprite_id: 2697, bounds: (1, 11, 10), dx: 0.0, dy: 3.0, dz: 0.0, z: 0.05, w: 21.0, h: 12.0, x_offs: 0.0, y_offs: -2.0, remap_x_adj: -3.0, path: "assets/opengfx/tiles/bus_stop_se_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2701, bounds: (16, 3, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 24.0, h: 17.0, x_offs: -22.0, y_offs: -6.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_se_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2705, bounds: (3, 13, 10), dx: 13.0, dy: 3.0, dz: 0.0, z: 0.07, w: 27.0, h: 21.0, x_offs: -3.0, y_offs: -17.0, remap_x_adj: 5.0, path: "assets/opengfx/tiles/bus_stop_se_build_c.png" },
    ],
    [ // SW
        RoadStopLayerGfx { sprite_id: 2698, bounds: (11, 1, 10), dx: 3.0, dy: 15.0, dz: 0.0, z: 0.05, w: 21.0, h: 12.0, x_offs: -17.0, y_offs: -13.0, remap_x_adj: -8.0, path: "assets/opengfx/tiles/bus_stop_sw_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2702, bounds: (3, 16, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 26.0, h: 18.0, x_offs: 3.0, y_offs: -2.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_sw_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2706, bounds: (13, 3, 10), dx: 3.0, dy: 0.0, dz: 0.0, z: 0.07, w: 26.0, h: 20.0, x_offs: -22.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_sw_build_c.png" },
    ],
    [ // NW
        RoadStopLayerGfx { sprite_id: 2699, bounds: (1, 11, 10), dx: 15.0, dy: 2.0, dz: 0.0, z: 0.05, w: 21.0, h: 12.0, x_offs: 0.0, y_offs: -19.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/bus_stop_nw_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2703, bounds: (16, 3, 10), dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 26.0, h: 19.0, x_offs: -26.0, y_offs: -9.0, remap_x_adj: -7.0, path: "assets/opengfx/tiles/bus_stop_nw_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2707, bounds: (3, 13, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.07, w: 27.0, h: 23.0, x_offs: -2.0, y_offs: -9.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_nw_build_c.png" },
    ],
];

pub const TRUCK_STOP_BUILD_LAYERS: [[RoadStopLayerGfx; 3]; 4] = [
    [ // NE
        RoadStopLayerGfx { sprite_id: 2712, bounds: (13, 1, 10), dx: 0.0, dy: 15.0, dz: 0.0, z: 0.05, w: 24.0, h: 24.0, x_offs: -23.0, y_offs: -19.0, remap_x_adj: -9.0, path: "assets/opengfx/tiles/truck_stop_ne_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2716, bounds: (3, 16, 10), dx: 13.0, dy: 0.0, dz: 0.0, z: 0.06, w: 37.0, h: 29.0, x_offs: -4.0, y_offs: -17.0, remap_x_adj: 7.0, path: "assets/opengfx/tiles/truck_stop_ne_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2720, bounds: (11, 1, 10), dx: 2.0, dy: 0.0, dz: 0.0, z: 0.07, w: 34.0, h: 21.0, x_offs: -26.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_ne_build_c.png" },
    ],
    [ // SE
        RoadStopLayerGfx { sprite_id: 2713, bounds: (1, 13, 10), dx: 15.0, dy: 3.0, dz: 0.0, z: 0.05, w: 29.0, h: 18.0, x_offs: -1.0, y_offs: -21.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/truck_stop_se_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2717, bounds: (16, 3, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 34.0, h: 29.0, x_offs: -31.0, y_offs: -11.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_se_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2721, bounds: (1, 11, 10), dx: 0.0, dy: 3.0, dz: 0.0, z: 0.07, w: 30.0, h: 23.0, x_offs: -5.0, y_offs: -9.0, remap_x_adj: -3.0, path: "assets/opengfx/tiles/truck_stop_se_build_c.png" },
    ],
    [ // SW
        RoadStopLayerGfx { sprite_id: 2714, bounds: (13, 1, 10), dx: 3.0, dy: 0.0, dz: 0.0, z: 0.05, w: 25.0, h: 20.0, x_offs: -23.0, y_offs: -6.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2718, bounds: (3, 16, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 36.0, h: 25.0, x_offs: -4.0, y_offs: -9.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2722, bounds: (11, 1, 10), dx: 3.0, dy: 15.0, dz: 0.0, z: 0.07, w: 35.0, h: 20.0, x_offs: -27.0, y_offs: -8.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_c.png" },
    ],
    [ // NW
        RoadStopLayerGfx { sprite_id: 2715, bounds: (1, 13, 10), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 25.0, h: 19.0, x_offs: -2.0, y_offs: -10.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_nw_build_a.png" },
        RoadStopLayerGfx { sprite_id: 2719, bounds: (16, 3, 10), dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 34.0, h: 27.0, x_offs: -27.0, y_offs: -15.0, remap_x_adj: -7.0, path: "assets/opengfx/tiles/truck_stop_nw_build_b.png" },
        RoadStopLayerGfx { sprite_id: 2723, bounds: (1, 11, 10), dx: 15.0, dy: 2.0, dz: 0.0, z: 0.07, w: 31.0, h: 23.0, x_offs: -4.0, y_offs: -27.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/truck_stop_nw_build_c.png" },
    ],
];

pub const BUS_STOP_DRIVE_THROUGH_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [
    [ // X
        RoadStopLayerGfx { sprite_id: 5980, bounds: (16, 3, 16), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 16.0, h: 9.0, x_offs: -12.0, y_offs: -2.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_x_w.png" },
        RoadStopLayerGfx { sprite_id: 5981, bounds: (16, 3, 16), dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 16.0, h: 9.0, x_offs: -4.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_x_e.png" },
    ],
    [ // Y
        RoadStopLayerGfx { sprite_id: 5978, bounds: (3, 16, 16), dx: 13.0, dy: 0.0, dz: 0.0, z: 0.05, w: 64.0, h: 40.0, x_offs: -47.0, y_offs: -17.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_y_w.png" },
        RoadStopLayerGfx { sprite_id: 5979, bounds: (3, 16, 16), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 64.0, h: 33.0, x_offs: -31.0, y_offs: -9.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_y_e.png" },
    ],
];

pub const TRUCK_STOP_DRIVE_THROUGH_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [
    [ // X
        RoadStopLayerGfx { sprite_id: 5984, bounds: (16, 3, 16), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 16.0, h: 9.0, x_offs: -2.0, y_offs: -2.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_x_w.png" },
        RoadStopLayerGfx { sprite_id: 5985, bounds: (16, 3, 16), dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 28.0, h: 13.0, x_offs: -12.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_x_e.png" },
    ],
    [ // Y
        RoadStopLayerGfx { sprite_id: 5982, bounds: (3, 16, 16), dx: 13.0, dy: 0.0, dz: 0.0, z: 0.05, w: 28.0, h: 13.0, x_offs: -14.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_y_w.png" },
        RoadStopLayerGfx { sprite_id: 5983, bounds: (3, 16, 16), dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 16.0, h: 9.0, x_offs: -10.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_y_e.png" },
    ],
];
