// @generated by scripts/gen_road_stop_gfx_data.py — no editar a mano.
// Fuente: OpenTTD station_land.h (_station_display_datas_67..74, 168..171) + PNG/NFO.
// remap_x_adj: corrección fina por capa (±1 unidad TILE_SEQ ≈ 4 px); 0 = solo RemapCoords+NFO.
// Modo gráfico detectado: 32bpp (assets/opengfx/.graphics_mode o carpetas).


#[derive(Debug, Clone, Copy)]
pub struct RoadStopLayerGfx {
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    pub z: f32,
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub remap_x_adj: f32,
    pub path: &'static str,
}

pub const BUS_STOP_BUILD_LAYERS: [[RoadStopLayerGfx; 3]; 4] = [
    [ // NE
        RoadStopLayerGfx { dx: 2.0, dy: 0.0, dz: 0.0, z: 0.05, w: 21.0, h: 13.0, x_offs: -29.0, y_offs: -2.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_ne_build_a.png" },
        RoadStopLayerGfx { dx: 13.0, dy: 0.0, dz: 0.0, z: 0.06, w: 26.0, h: 22.0, x_offs: 1.0, y_offs: -12.0, remap_x_adj: 7.0, path: "assets/opengfx/tiles/bus_stop_ne_build_b.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 13.0, dz: 0.0, z: 0.07, w: 24.0, h: 23.0, x_offs: -24.0, y_offs: -8.0, remap_x_adj: -13.0, path: "assets/opengfx/tiles/bus_stop_ne_build_c.png" },
    ],
    [ // SE
        RoadStopLayerGfx { dx: 0.0, dy: 3.0, dz: 0.0, z: 0.05, w: 21.0, h: 13.0, x_offs: 0.0, y_offs: -3.0, remap_x_adj: -3.0, path: "assets/opengfx/tiles/bus_stop_se_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 26.0, h: 19.0, x_offs: -26.0, y_offs: -4.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_se_build_b.png" },
        RoadStopLayerGfx { dx: 13.0, dy: 3.0, dz: 0.0, z: 0.07, w: 26.0, h: 21.0, x_offs: -5.0, y_offs: -18.0, remap_x_adj: 5.0, path: "assets/opengfx/tiles/bus_stop_se_build_c.png" },
    ],
    [ // SW
        RoadStopLayerGfx { dx: 3.0, dy: 15.0, dz: 0.0, z: 0.05, w: 21.0, h: 13.0, x_offs: -18.0, y_offs: -13.0, remap_x_adj: -8.0, path: "assets/opengfx/tiles/bus_stop_sw_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 24.0, h: 19.0, x_offs: 3.0, y_offs: -3.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_sw_build_b.png" },
        RoadStopLayerGfx { dx: 3.0, dy: 0.0, dz: 0.0, z: 0.07, w: 27.0, h: 21.0, x_offs: -19.0, y_offs: -8.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_sw_build_c.png" },
    ],
    [ // NW
        RoadStopLayerGfx { dx: 15.0, dy: 2.0, dz: 0.0, z: 0.05, w: 21.0, h: 13.0, x_offs: 1.0, y_offs: -19.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/bus_stop_nw_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 25.0, h: 19.0, x_offs: -24.0, y_offs: -10.0, remap_x_adj: -7.0, path: "assets/opengfx/tiles/bus_stop_nw_build_b.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.07, w: 26.0, h: 21.0, x_offs: 1.0, y_offs: -5.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_nw_build_c.png" },
    ],
];

pub const TRUCK_STOP_BUILD_LAYERS: [[RoadStopLayerGfx; 3]; 4] = [
    [ // NE
        RoadStopLayerGfx { dx: 0.0, dy: 15.0, dz: 0.0, z: 0.05, w: 28.0, h: 20.0, x_offs: -25.0, y_offs: -14.0, remap_x_adj: -9.0, path: "assets/opengfx/tiles/truck_stop_ne_build_a.png" },
        RoadStopLayerGfx { dx: 13.0, dy: 0.0, dz: 0.0, z: 0.06, w: 36.0, h: 25.0, x_offs: -5.0, y_offs: -13.0, remap_x_adj: 7.0, path: "assets/opengfx/tiles/truck_stop_ne_build_b.png" },
        RoadStopLayerGfx { dx: 2.0, dy: 0.0, dz: 0.0, z: 0.07, w: 28.0, h: 18.0, x_offs: -21.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_ne_build_c.png" },
    ],
    [ // SE
        RoadStopLayerGfx { dx: 15.0, dy: 3.0, dz: 0.0, z: 0.05, w: 28.0, h: 20.0, x_offs: -3.0, y_offs: -23.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/truck_stop_se_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 36.0, h: 25.0, x_offs: -31.0, y_offs: -8.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_se_build_b.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 3.0, dz: 0.0, z: 0.07, w: 25.0, h: 19.0, x_offs: 0.0, y_offs: -6.0, remap_x_adj: -3.0, path: "assets/opengfx/tiles/truck_stop_se_build_c.png" },
    ],
    [ // SW
        RoadStopLayerGfx { dx: 3.0, dy: 0.0, dz: 0.0, z: 0.05, w: 28.0, h: 20.0, x_offs: -25.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 36.0, h: 26.0, x_offs: -3.0, y_offs: -9.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_b.png" },
        RoadStopLayerGfx { dx: 3.0, dy: 15.0, dz: 0.0, z: 0.07, w: 28.0, h: 16.0, x_offs: -25.0, y_offs: -5.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_sw_build_c.png" },
    ],
    [ // NW
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 28.0, h: 20.0, x_offs: 5.0, y_offs: -4.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_nw_build_a.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 36.0, h: 28.0, x_offs: -29.0, y_offs: -16.0, remap_x_adj: -7.0, path: "assets/opengfx/tiles/truck_stop_nw_build_b.png" },
        RoadStopLayerGfx { dx: 15.0, dy: 2.0, dz: 0.0, z: 0.07, w: 25.0, h: 20.0, x_offs: -3.0, y_offs: -26.0, remap_x_adj: 8.0, path: "assets/opengfx/tiles/truck_stop_nw_build_c.png" },
    ],
];

pub const BUS_STOP_DRIVE_THROUGH_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [
    [ // X
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 17.0, h: 9.0, x_offs: -14.0, y_offs: -4.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_x_w.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 18.0, h: 9.0, x_offs: -1.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_x_e.png" },
    ],
    [ // Y
        RoadStopLayerGfx { dx: 13.0, dy: 0.0, dz: 0.0, z: 0.05, w: 16.0, h: 11.0, x_offs: 0.0, y_offs: -1.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_y_w.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 32.0, h: 24.0, x_offs: -15.0, y_offs: -15.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/bus_stop_dt_y_e.png" },
    ],
];

pub const TRUCK_STOP_DRIVE_THROUGH_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [
    [ // X
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.05, w: 17.0, h: 9.0, x_offs: 0.0, y_offs: -4.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_x_w.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 13.0, dz: 0.0, z: 0.06, w: 32.0, h: 16.0, x_offs: -15.0, y_offs: -11.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_x_e.png" },
    ],
    [ // Y
        RoadStopLayerGfx { dx: 13.0, dy: 0.0, dz: 0.0, z: 0.05, w: 32.0, h: 16.0, x_offs: -15.0, y_offs: -11.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_y_w.png" },
        RoadStopLayerGfx { dx: 0.0, dy: 0.0, dz: 0.0, z: 0.06, w: 18.0, h: 9.0, x_offs: -15.0, y_offs: -7.0, remap_x_adj: 0.0, path: "assets/opengfx/tiles/truck_stop_dt_y_e.png" },
    ],
];
