// @generated by scripts/gen_road_depot_gfx_data.py — no editar a mano.
// Fuente: OpenTTD road_land.h (_road_depot_NE..NW) + PNG/NFO.
// Modo gráfico detectado: 32bpp.

#[derive(Debug, Clone, Copy)]
pub struct RoadDepotLayerGfx {
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    pub z: f32,
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub remap_x_adj: f32,
    pub path: &'static str,
}

pub const ROAD_DEPOT_GROUND_PATH: &str = "assets/opengfx/tiles/road_depot_ground.png";

pub const ROAD_DEPOT_BUILD_LAYERS: [&[RoadDepotLayerGfx]; 4] = [
    &[
        // NE
        RoadDepotLayerGfx {
            dx: 0.0,
            dy: 15.0,
            dz: 0.0,
            z: 0.05,
            w: 60.0,
            h: 47.0,
            x_offs: -59.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/rail_1412.png",
        },
    ],
    &[
        // SE
        RoadDepotLayerGfx {
            dx: 0.0,
            dy: 0.0,
            dz: 0.0,
            z: 0.05,
            w: 12.0,
            h: 12.0,
            x_offs: 18.0,
            y_offs: 5.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_0.png",
        },
        RoadDepotLayerGfx {
            dx: 15.0,
            dy: 0.0,
            dz: 0.0,
            z: 0.06,
            w: 60.0,
            h: 47.0,
            x_offs: 1.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_1.png",
        },
    ],
    &[
        // SW
        RoadDepotLayerGfx {
            dx: 0.0,
            dy: 0.0,
            dz: 0.0,
            z: 0.05,
            w: 12.0,
            h: 12.0,
            x_offs: -28.0,
            y_offs: 5.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_2.png",
        },
        RoadDepotLayerGfx {
            dx: 0.0,
            dy: 15.0,
            dz: 0.0,
            z: 0.06,
            w: 60.0,
            h: 47.0,
            x_offs: -59.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_3.png",
        },
    ],
    &[
        // NW
        RoadDepotLayerGfx {
            dx: 15.0,
            dy: 0.0,
            dz: 0.0,
            z: 0.05,
            w: 60.0,
            h: 47.0,
            x_offs: 1.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/rail_1413.png",
        },
    ],
];
