// @generated by scripts/gen_road_depot_gfx_data.py — no editar a mano.
// Fuente: OpenTTD road_land.h (_road_depot_NE..NW) + PNG/NFO.
// Modo gráfico detectado: 8bpp.

#[derive(Debug, Clone, Copy)]
pub struct RoadDepotLayerGfx {
    /// Sprite global de OpenTTD emitido por `DrawRailTileSeq`.
    pub sprite_id: u32,
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    /// Caja de ordenación `TILE_SEQ_LINE` (unidades de mapa, no píxeles PNG).
    pub sx: i32,
    pub sy: i32,
    pub z: f32,
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub remap_x_adj: f32,
    pub path: &'static str,
}

/// `SPR_AIRPORT_APRON` / suelo de `_road_depot` en `road_land.h`.
pub const ROAD_DEPOT_GROUND_SPRITE_ID: u32 = 2634;

pub const ROAD_DEPOT_GROUND_PATH: &str = "assets/opengfx/tiles/road_depot_ground.png";

pub const ROAD_DEPOT_BUILD_LAYERS: [&[RoadDepotLayerGfx]; 4] = [
    &[
        // NE
        RoadDepotLayerGfx {
            sprite_id: 1412,
            dx: 0.0,
            dy: 15.0,
            dz: 0.0,
            sx: 16,
            sy: 1,
            z: 0.05,
            w: 60.0,
            h: 47.0,
            x_offs: -59.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/rail_1412.png",
        },
    ],
    &[
        // SE
        RoadDepotLayerGfx {
            sprite_id: 1408,
            dx: 0.0,
            dy: 0.0,
            dz: 0.0,
            sx: 1,
            sy: 16,
            z: 0.05,
            w: 12.0,
            h: 12.0,
            x_offs: 19.0,
            y_offs: 5.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_0.png",
        },
        RoadDepotLayerGfx {
            sprite_id: 1409,
            dx: 15.0,
            dy: 0.0,
            dz: 0.0,
            sx: 1,
            sy: 16,
            z: 0.06,
            w: 60.0,
            h: 47.0,
            x_offs: 1.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_1.png",
        },
    ],
    &[
        // SW
        RoadDepotLayerGfx {
            sprite_id: 1410,
            dx: 0.0,
            dy: 0.0,
            dz: 0.0,
            sx: 16,
            sy: 1,
            z: 0.05,
            w: 12.0,
            h: 12.0,
            x_offs: -29.0,
            y_offs: 5.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_2.png",
        },
        RoadDepotLayerGfx {
            sprite_id: 1411,
            dx: 0.0,
            dy: 15.0,
            dz: 0.0,
            sx: 16,
            sy: 1,
            z: 0.06,
            w: 60.0,
            h: 47.0,
            x_offs: -59.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_depot_3.png",
        },
    ],
    &[
        // NW
        RoadDepotLayerGfx {
            sprite_id: 1413,
            dx: 15.0,
            dy: 0.0,
            dz: 0.0,
            sx: 1,
            sy: 16,
            z: 0.05,
            w: 60.0,
            h: 47.0,
            x_offs: 1.0,
            y_offs: -32.0,
            remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/rail_1413.png",
        },
    ],
];
