// @generated by scripts/extract_road_waypoint_sprites.py — no editar a mano.
// Fuente: reference/openttd-15.3-oracle/media/baseset/openttd/road_waypoints.nfo.

/// IDs globales `SPR_ROAD_WAYPOINT_*` del GRF oficial.
#[allow(dead_code)]
pub const ROAD_WAYPOINT_SPRITE_IDS: [u32; 4] = [6141, 6142, 6143, 6144];
#[allow(dead_code)]
pub const ROAD_WAYPOINT_SPRITE_PATHS: [&str; 4] = [
    "assets/opengfx/tiles/road_waypoint_y_w.png",
    "assets/opengfx/tiles/road_waypoint_y_e.png",
    "assets/opengfx/tiles/road_waypoint_x_w.png",
    "assets/opengfx/tiles/road_waypoint_x_e.png",
];

#[allow(dead_code)]
pub const ROAD_WAYPOINT_SPRITE_META: [(u32, f32, f32, f32, f32); 4] = [
    (6141, 64.0, 40.0, -5.0, -22.0),
    (6142, 64.0, 40.0, -31.0, -9.0),
    (6143, 64.0, 35.0, -31.0, -4.0),
    (6144, 64.0, 35.0, -57.0, -17.0),
];


pub const ROAD_WAYPOINT_BUILD_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [
    [
        RoadStopLayerGfx {
            sprite_id: 6143, bounds: (16, 3, 16), dx: 0.0, dy: 0.0, dz: 0.0,
            z: 0.05, w: 64.0, h: 35.0, x_offs: -31.0, y_offs: -4.0, remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_waypoint_x_w.png",
        },
        RoadStopLayerGfx {
            sprite_id: 6144, bounds: (16, 3, 16), dx: 0.0, dy: 13.0, dz: 0.0,
            z: 0.06, w: 64.0, h: 35.0, x_offs: -57.0, y_offs: -17.0, remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_waypoint_x_e.png",
        },
    ],
    [
        RoadStopLayerGfx {
            sprite_id: 6141, bounds: (3, 16, 16), dx: 13.0, dy: 0.0, dz: 0.0,
            z: 0.05, w: 64.0, h: 40.0, x_offs: -5.0, y_offs: -22.0, remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_waypoint_y_w.png",
        },
        RoadStopLayerGfx {
            sprite_id: 6142, bounds: (3, 16, 16), dx: 0.0, dy: 0.0, dz: 0.0,
            z: 0.06, w: 64.0, h: 40.0, x_offs: -31.0, y_offs: -9.0, remap_x_adj: 0.0,
            path: "assets/opengfx/tiles/road_waypoint_y_e.png",
        },
    ],
];
