// @generated by scripts/extract_tramway_sprites.py — no editar a mano.
// Fuente: bloque Action5 0x0B del GRF openttd.nfo.
// NFO: reference/openttd-15.3-oracle/build/media/baseset/openttd/sprites/openttd.nfo.
#![cfg_attr(rustfmt, rustfmt_skip)]

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TramwaySpriteGfx {
    pub width: f32,
    pub height: f32,
    pub x_offs: f32,
    pub y_offs: f32,
}

/// 119 offsets de `SPR_TRAMWAY_BASE`, incluyendo overlay, catenaria, túnel y puente.
pub const TRAMWAY_SPRITE_GFX: [TramwaySpriteGfx; 119] = [
    TramwaySpriteGfx { width: 20.0, height: 13.0, x_offs: 0.0, y_offs: 4.0 }, // offset 0
    TramwaySpriteGfx { width: 20.0, height: 13.0, x_offs: 0.0, y_offs: 4.0 }, // offset 1
    TramwaySpriteGfx { width: 64.0, height: 36.0, x_offs: -18.0, y_offs: -8.0 }, // offset 2
    TramwaySpriteGfx { width: 62.0, height: 36.0, x_offs: -16.0, y_offs: -8.0 }, // offset 3
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 4
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 5
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 6
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 7
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 8
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 9
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 10
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 11
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 12
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 13
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 14
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 15
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 16
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 17
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 18
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 19
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 20
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 21
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 22
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 23
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 24
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 25
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 26
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 27
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 28
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 29
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 30
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 31
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 32
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 33
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 34
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 35
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 36
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 37
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 38
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 39
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 40
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 41
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 42
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 43
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 44
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 45
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 46
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 47
    TramwaySpriteGfx { width: 20.0, height: 20.0, x_offs: 0.0, y_offs: 0.0 }, // offset 48
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 49
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: 2.0, y_offs: -49.0 }, // offset 50
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 51
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: -62.0, y_offs: -49.0 }, // offset 52
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: -62.0, y_offs: -49.0 }, // offset 53
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: 2.0, y_offs: -49.0 }, // offset 54
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 55
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 56
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 57
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 58
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 59
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 60
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 61
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 62
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 63
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 64
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 65
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 66
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 67
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 68
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 69
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 70
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 71
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 72
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 73
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 74
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 75
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 76
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 77
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 78
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 79
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 80
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 81
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 82
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 83
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 84
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 85
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 86
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 87
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 88
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 89
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 90
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 91
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 92
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 93
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 94
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 95
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 96
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 97
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 98
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 99
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 100
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 101
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 102
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 103
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 104
    TramwaySpriteGfx { width: 64.0, height: 56.0, x_offs: -31.0, y_offs: -25.0 }, // offset 105
    TramwaySpriteGfx { width: 64.0, height: 48.0, x_offs: -31.0, y_offs: -17.0 }, // offset 106
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 107
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 108
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 109
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 110
    TramwaySpriteGfx { width: 64.0, height: 23.0, x_offs: -31.0, y_offs: 0.0 }, // offset 111
    TramwaySpriteGfx { width: 64.0, height: 39.0, x_offs: -31.0, y_offs: -8.0 }, // offset 112
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 113
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: 2.0, y_offs: -49.0 }, // offset 114
    TramwaySpriteGfx { width: 64.0, height: 31.0, x_offs: -31.0, y_offs: 0.0 }, // offset 115
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: -62.0, y_offs: -49.0 }, // offset 116
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: -62.0, y_offs: -49.0 }, // offset 117
    TramwaySpriteGfx { width: 62.0, height: 64.0, x_offs: 2.0, y_offs: -49.0 }, // offset 118
];
