// @generated by scripts/gen_vehicle_gfx_data.py — no editar a mano.
// Fuente: OpenGFX bus/camión MPS + Kirby Paul Tank (sprites 2921..2928).
// Modo gráfico detectado: 32bpp.

#[derive(Debug, Clone, Copy)]
pub struct VehicleLayerGfx {
    pub w: f32,
    pub h: f32,
    pub x_offs: f32,
    pub y_offs: f32,
    pub path: &'static str,
}

/// Índice = `Vehicle::render_direction()` (`OpenTTD` `Direction` 0..7).
pub const BUS_VEHICLE_LAYERS: [VehicleLayerGfx; 8] = [
    // N (sprite 3092)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_bus_n.png",
    },
    // NE (sprite 3093)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_ne.png",
    },
    // E (sprite 3094)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -14.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_bus_e.png",
    },
    // SE (sprite 3095)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_se.png",
    },
    // S (sprite 3096)
    VehicleLayerGfx {
        w: 8.0,
        h: 17.0,
        x_offs: -3.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_bus_s.png",
    },
    // SW (sprite 3097)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_sw.png",
    },
    // W (sprite 3098)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -14.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_bus_w.png",
    },
    // NW (sprite 3099)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_nw.png",
    },
];

pub const BUS_VEHICLE_LAYERS_LOADED: [VehicleLayerGfx; 8] = [
    // N (sprite 3180)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_bus_n_loaded.png",
    },
    // NE (sprite 3181)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_ne_loaded.png",
    },
    // E (sprite 3182)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_bus_e_loaded.png",
    },
    // SE (sprite 3183)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_se_loaded.png",
    },
    // S (sprite 3184)
    VehicleLayerGfx {
        w: 8.0,
        h: 17.0,
        x_offs: -3.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_bus_s_loaded.png",
    },
    // SW (sprite 3185)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_sw_loaded.png",
    },
    // W (sprite 3186)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_bus_w_loaded.png",
    },
    // NW (sprite 3187)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_bus_nw_loaded.png",
    },
];

pub const TRUCK_VEHICLE_LAYERS: [VehicleLayerGfx; 8] = [
    // N (sprite 3100)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_truck_n.png",
    },
    // NE (sprite 3101)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_truck_ne.png",
    },
    // E (sprite 3102)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_truck_e.png",
    },
    // SE (sprite 3103)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -6.0,
        y_offs: -5.0,
        path: "assets/opengfx/tiles/vehicle_truck_se.png",
    },
    // S (sprite 3104)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_truck_s.png",
    },
    // SW (sprite 3105)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -14.0,
        y_offs: -5.0,
        path: "assets/opengfx/tiles/vehicle_truck_sw.png",
    },
    // W (sprite 3106)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_truck_w.png",
    },
    // NW (sprite 3107)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_truck_nw.png",
    },
];

pub const TRUCK_VEHICLE_LAYERS_LOADED: [VehicleLayerGfx; 8] = [
    // N (sprite 3188)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_truck_n_loaded.png",
    },
    // NE (sprite 3189)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_truck_ne_loaded.png",
    },
    // E (sprite 3190)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_truck_e_loaded.png",
    },
    // SE (sprite 3191)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -6.0,
        y_offs: -5.0,
        path: "assets/opengfx/tiles/vehicle_truck_se_loaded.png",
    },
    // S (sprite 3192)
    VehicleLayerGfx {
        w: 8.0,
        h: 18.0,
        x_offs: -3.0,
        y_offs: -10.4,
        path: "assets/opengfx/tiles/vehicle_truck_s_loaded.png",
    },
    // SW (sprite 3193)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -14.0,
        y_offs: -5.0,
        path: "assets/opengfx/tiles/vehicle_truck_sw_loaded.png",
    },
    // W (sprite 3194)
    VehicleLayerGfx {
        w: 27.0,
        h: 12.0,
        x_offs: -13.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_truck_w_loaded.png",
    },
    // NW (sprite 3195)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_truck_nw_loaded.png",
    },
];

pub const TRAIN_VEHICLE_LAYERS: [VehicleLayerGfx; 8] = [
    // N (sprite 2921)
    VehicleLayerGfx {
        w: 8.0,
        h: 20.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_train_n.png",
    },
    // NE (sprite 2922)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_ne.png",
    },
    // E (sprite 2923)
    VehicleLayerGfx {
        w: 28.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_e.png",
    },
    // SE (sprite 2924)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_se.png",
    },
    // S (sprite 2925)
    VehicleLayerGfx {
        w: 8.0,
        h: 20.0,
        x_offs: -3.0,
        y_offs: -10.0,
        path: "assets/opengfx/tiles/vehicle_train_s.png",
    },
    // SW (sprite 2926)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_sw.png",
    },
    // W (sprite 2927)
    VehicleLayerGfx {
        w: 28.0,
        h: 12.0,
        x_offs: -15.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_w.png",
    },
    // NW (sprite 2928)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_nw.png",
    },
];

pub const TRAIN_VEHICLE_LAYERS_T0: [VehicleLayerGfx; 8] = [
    // N (sprite 2905)
    VehicleLayerGfx {
        w: 8.0,
        h: 21.0,
        x_offs: -3.0,
        y_offs: -11.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_n.png",
    },
    // NE (sprite 2906)
    VehicleLayerGfx {
        w: 20.0,
        h: 15.0,
        x_offs: -14.0,
        y_offs: -8.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_ne.png",
    },
    // E (sprite 2907)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_e.png",
    },
    // SE (sprite 2908)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_se.png",
    },
    // S (sprite 2909)
    VehicleLayerGfx {
        w: 8.0,
        h: 21.0,
        x_offs: -3.0,
        y_offs: -11.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_s.png",
    },
    // SW (sprite 2910)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_sw.png",
    },
    // W (sprite 2911)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_w.png",
    },
    // NW (sprite 2912)
    VehicleLayerGfx {
        w: 20.0,
        h: 15.0,
        x_offs: -6.0,
        y_offs: -8.0,
        path: "assets/opengfx/tiles/vehicle_train_t0_nw.png",
    },
];

pub const TRAIN_VEHICLE_LAYERS_T1: [VehicleLayerGfx; 8] = [
    // N (sprite 2913)
    VehicleLayerGfx {
        w: 8.0,
        h: 22.0,
        x_offs: -3.0,
        y_offs: -12.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_n.png",
    },
    // NE (sprite 2914)
    VehicleLayerGfx {
        w: 20.0,
        h: 15.0,
        x_offs: -14.0,
        y_offs: -8.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_ne.png",
    },
    // E (sprite 2915)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_e.png",
    },
    // SE (sprite 2916)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_se.png",
    },
    // S (sprite 2917)
    VehicleLayerGfx {
        w: 8.0,
        h: 22.0,
        x_offs: -3.0,
        y_offs: -12.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_s.png",
    },
    // SW (sprite 2918)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_sw.png",
    },
    // W (sprite 2919)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_w.png",
    },
    // NW (sprite 2920)
    VehicleLayerGfx {
        w: 20.0,
        h: 15.0,
        x_offs: -6.0,
        y_offs: -8.0,
        path: "assets/opengfx/tiles/vehicle_train_t1_nw.png",
    },
];

pub const TRAIN_VEHICLE_LAYERS_TDIESEL: [VehicleLayerGfx; 8] = [
    // N (sprite 2949)
    VehicleLayerGfx {
        w: 8.0,
        h: 21.0,
        x_offs: -3.0,
        y_offs: -11.0,
        path: "assets/opengfx/tiles/vehicle_train_td_n.png",
    },
    // NE (sprite 2950)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_td_ne.png",
    },
    // E (sprite 2951)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_td_e.png",
    },
    // SE (sprite 2952)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_td_se.png",
    },
    // S (sprite 2953)
    VehicleLayerGfx {
        w: 8.0,
        h: 21.0,
        x_offs: -3.0,
        y_offs: -11.0,
        path: "assets/opengfx/tiles/vehicle_train_td_s.png",
    },
    // SW (sprite 2954)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -14.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_td_sw.png",
    },
    // W (sprite 2955)
    VehicleLayerGfx {
        w: 29.0,
        h: 12.0,
        x_offs: -16.0,
        y_offs: -6.0,
        path: "assets/opengfx/tiles/vehicle_train_td_w.png",
    },
    // NW (sprite 2956)
    VehicleLayerGfx {
        w: 20.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_td_nw.png",
    },
];

pub const TRAIN_VEHICLE_LAYERS_TELECTRIC: [VehicleLayerGfx; 8] = [
    // N (sprite 2965)
    VehicleLayerGfx {
        w: 8.0,
        h: 19.0,
        x_offs: -3.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_te_n.png",
    },
    // NE (sprite 2966)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -14.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_train_te_ne.png",
    },
    // E (sprite 2967)
    VehicleLayerGfx {
        w: 29.0,
        h: 15.0,
        x_offs: -16.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_te_e.png",
    },
    // SE (sprite 2968)
    VehicleLayerGfx {
        w: 19.0,
        h: 16.0,
        x_offs: -6.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_te_se.png",
    },
    // S (sprite 2969)
    VehicleLayerGfx {
        w: 8.0,
        h: 21.0,
        x_offs: -3.0,
        y_offs: -11.0,
        path: "assets/opengfx/tiles/vehicle_train_te_s.png",
    },
    // SW (sprite 2970)
    VehicleLayerGfx {
        w: 19.0,
        h: 16.0,
        x_offs: -13.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_te_sw.png",
    },
    // W (sprite 2971)
    VehicleLayerGfx {
        w: 29.0,
        h: 15.0,
        x_offs: -16.0,
        y_offs: -9.0,
        path: "assets/opengfx/tiles/vehicle_train_te_w.png",
    },
    // NW (sprite 2972)
    VehicleLayerGfx {
        w: 20.0,
        h: 14.0,
        x_offs: -6.0,
        y_offs: -7.0,
        path: "assets/opengfx/tiles/vehicle_train_te_nw.png",
    },
];
