//! Tablas del generador de nombres de ciudades de `OpenTTD`.
//!
//! Generado por `scripts/gen_townname_tables.py` desde
//! `OpenTTD/src/table/townname.h`. NO EDITAR A MANO.

use super::{CzechGender, CzechNameAdj, CzechNameSubst};

pub(super) static NAME_ORIGINAL_ENGLISH_1: &[&str] = &["Great ", "Little ", "New ", "Fort "];

pub(super) static NAME_ORIGINAL_ENGLISH_2: &[&str] = &[
    "Wr", "B", "C", "Ch", "Br", "D", "Dr", "F", "Fr", "Fl", "G", "Gr", "H", "L", "M", "N", "P",
    "Pr", "Pl", "R", "S", "S", "Sl", "T", "Tr", "W",
];

pub(super) static NAME_ORIGINAL_ENGLISH_3: &[&str] = &["ar", "a", "e", "in", "on", "u", "un", "en"];

pub(super) static NAME_ORIGINAL_ENGLISH_4: &[&str] = &["n", "ning", "ding", "d", "", "t", "fing"];

pub(super) static NAME_ORIGINAL_ENGLISH_5: &[&str] = &[
    "ville", "ham", "field", "ton", "town", "bridge", "bury", "wood", "ford", "hall", "ston",
    "way", "stone", "borough", "ley", "head", "bourne", "pool", "worth", "hill", "well", "hattan",
    "burg",
];

pub(super) static NAME_ORIGINAL_ENGLISH_6: &[&str] = &[
    "-on-sea", " Bay", " Market", " Cross", " Bridge", " Falls", " City", " Ridge", " Springs",
];

pub(super) static NAME_ADDITIONAL_ENGLISH_PREFIX: &[&str] =
    &["Great ", "Little ", "New ", "Fort ", "St. ", "Old "];

pub(super) static NAME_ADDITIONAL_ENGLISH_1A: &[&str] = &[
    "Pen", "Lough", "Stam", "Aber", "Acc", "Ex", "Ax", "Bre", "Cum", "Dun", "Fin", "Inver", "Kin",
    "Mon", "Nan", "Nant", "Pit", "Pol", "Pont", "Strath", "Tre", "Tilly", "Beck", "Canter", "Bath",
    "Liver", "Mal", "Ox", "Bletch", "Maccles", "Grim", "Wind", "Sher", "Gates", "Orp", "Brom",
    "Lewis", "Whit", "White", "Worm", "Tyne", "Avon", "Stan",
];

pub(super) static NAME_ADDITIONAL_ENGLISH_1B1: &[&str] = &[
    "Wr", "B", "C", "Ch", "Br", "D", "Dr", "F", "Fr", "Fl", "G", "Gr", "H", "L", "M", "N", "P",
    "Pr", "Pl", "R", "S", "S", "Sl", "T", "Tr", "W",
];

pub(super) static NAME_ADDITIONAL_ENGLISH_1B2: &[&str] = &[
    "ar", "a", "e", "in", "on", "u", "o", "ee", "es", "ea", "un", "en",
];

pub(super) static NAME_ADDITIONAL_ENGLISH_1B3A: &[&str] = &["n", "d", "", "t", "", ""];

pub(super) static NAME_ADDITIONAL_ENGLISH_1B3B: &[&str] = &["ning", "ding", "fing"];

pub(super) static NAME_ADDITIONAL_ENGLISH_2: &[&str] = &[
    "ville", "ham", "field", "ton", "town", "borough", "bridge", "bury", "wood", "ditch", "ford",
    "hall", "dean", "leigh", "dore", "ston", "stow", "church", "wich", "low", "way", "stone",
    "minster", "ley", "head", "bourne", "pool", "worth", "hill", "well", "hattan", "burg", "berg",
    "burgh", "port", "stoke", "haven", "stable", "stock", "side", "brook", "don", "den", "down",
    "nor", "grove", "combe", "by", "say", "ney", "chester", "dale", "ness", "shaw", "thwaite",
];

pub(super) static NAME_ADDITIONAL_ENGLISH_3: &[&str] = &[
    "-on-sea", " Bay", " Market", " Beeches", " Common", " Park", " Heath", " Marsh", " Green",
    " Castle", " End", " Rivers", " Cross", " Bridge", " Falls", " City", " Ridge", " Springs",
];

pub(super) static NAME_AUSTRIAN_A1: &[&str] =
    &["Bad ", "Deutsch ", "Gross ", "Klein ", "Markt ", "Maria "];

pub(super) static NAME_AUSTRIAN_A2: &[&str] = &[
    "Aus",
    "Alten",
    "Braun",
    "V\u{00f6}sl",
    "Mittern",
    "Nuss",
    "Neu",
    "Walters",
    "Breiten",
    "Eisen",
    "Feld",
    "Mittern",
    "Gall",
    "Obern",
    "Grat",
    "Heiligen",
    "Hof",
    "Holla",
    "Stein",
    "Eber",
    "Eggen",
    "Enzers",
    "Frauen",
    "Herren",
    "Hof",
    "H\u{00fc}tt",
    "Kaisers",
    "K\u{00f6}nigs",
    "Knittel",
    "Lang",
    "Ober",
    "Ollers",
    "Pfaffen",
    "Potten",
    "Salz",
    "Schwarz",
    "Stocker",
    "Unter",
    "Utten",
    "V\u{00f6}sen",
    "Vill",
    "Weissen",
];

pub(super) static NAME_AUSTRIAN_A3: &[&str] = &[
    "see", "bach", "dorf", "ach", "stein", "hofen", "au", "ach", "kirch", "kirchen", "kreuz",
    "brunn", "siedl", "markt", "wang", "haag",
];

pub(super) static NAME_AUSTRIAN_A4: &[&str] = &[
    "Bruck",
    "Brunn",
    "Gams",
    "Grein",
    "Ried",
    "Faak",
    "Zell",
    "Spital",
    "Kirchberg",
    "Saal",
    "Taferl",
    "Wald",
];

pub(super) static NAME_AUSTRIAN_A5: &[&str] = &["St. ", "Sankt "];

pub(super) static NAME_AUSTRIAN_A6: &[&str] = &[
    "Aegyd",
    "Andr\u{00e4}",
    "Georgen",
    "Jakob",
    "Johann",
    "Leonhard",
    "Marein",
    "Lorenzen",
    "Margarethen",
    "Martin",
    "Michael",
    "Nikolai",
    "Oswald",
    "Peter",
    "P\u{00f6}lten",
    "Stefan",
    "Stephan",
    "Thomas",
    "Veit",
    "Wolfgang",
];

pub(super) static NAME_AUSTRIAN_F1: &[&str] = &[" an der ", " ob der "];

pub(super) static NAME_AUSTRIAN_F2: &[&str] = &[
    "Donau", "Steyr", "Lafnitz", "Leitha", "Thaya", "Gail", "Drau", "Salzach", "Ybbs", "Traisen",
    "Enns", "Mur", "Ill",
];

pub(super) static NAME_AUSTRIAN_B1: &[&str] = &[" am "];

pub(super) static NAME_AUSTRIAN_B2: &[&str] = &[
    "Brenner",
    "Dachstein",
    "Gebirge",
    "Grossglockner",
    "Hausruck",
    "Semmering",
    "Wagram",
    "Wechsel",
    "Wilden Kaiser",
    "Ziller",
];

pub(super) static NAME_GERMAN_REAL: &[&str] = &[
    "Berlin",
    "Bonn",
    "Bremen",
    "Cottbus",
    "Chemnitz",
    "Dortmund",
    "Dresden",
    "Erfurt",
    "Erlangen",
    "Essen",
    "Fulda",
    "Gera",
    "Kassel",
    "Kiel",
    "K\u{00f6}ln",
    "L\u{00fc}beck",
    "Magdeburg",
    "M\u{00fc}nchen",
    "Potsdam",
    "Stuttgart",
    "Wiesbaden",
];

pub(super) static NAME_GERMAN_PRE: &[&str] = &["Bad ", "Klein ", "Neu "];

pub(super) static NAME_GERMAN_1: &[&str] = &[
    "Alb",
    "Als",
    "Ander",
    "Arns",
    "Bruns",
    "Bam",
    "Biele",
    "Cloppen",
    "Co",
    "Duis",
    "D\u{00fc}ssel",
    "Dannen",
    "Elb",
    "Els",
    "Elster",
    "Eichen",
    "Ems",
    "Fahr",
    "Falken",
    "Flens",
    "Frank",
    "Frei",
    "Freuden",
    "Fried",
    "F\u{00fc}rsten",
    "Hahn",
    "Ham",
    "Harz",
    "Heidel",
    "Hers",
    "Herz",
    "Holz",
    "Hildes",
    "Inns",
    "Ilsen",
    "Ingols",
    "Kel",
    "Kies",
    "Korn",
    "Kor",
    "Kreuz",
    "Kulm",
    "Langen",
    "Lim",
    "Lohr",
    "L\u{00fc}ne",
    "Mel",
    "Michels",
    "M\u{00fc}hl",
    "Naum",
    "Nest",
    "Nord",
    "Nort",
    "Nien",
    "Nidda",
    "Nieder",
    "N\u{00fc}rn",
    "Ober",
    "Offen",
    "Osna",
    "Olden",
    "Ols",
    "Oranien",
    "Pader",
    "Quedlin",
    "Quer",
    "Ravens",
    "Regens",
    "Rott",
    "Ros",
    "R\u{00fc}ssels",
    "Saal",
    "Saar",
    "Salz",
    "Sch\u{00f6}ne",
    "Schwein",
    "Sonder",
    "Sonnen",
    "Stein",
    "Strals",
    "Straus",
    "S\u{00fc}d",
    "Ton",
    "Unter",
    "Ur",
    "Vor",
    "Wald",
    "War",
    "Wert",
    "Wester",
    "Witten",
    "Wolfs",
    "W\u{00fc}rz",
];

pub(super) static NAME_GERMAN_2: &[&str] = &[
    "bach",
    "berg",
    "br\u{00fc}ck",
    "br\u{00fc}cken",
    "burg",
    "dorf",
    "feld",
    "furt",
    "hausen",
    "haven",
    "heim",
    "horst",
    "mund",
    "m\u{00fc}nster",
    "stadt",
    "wald",
];

pub(super) static NAME_GERMAN_3_AN_DER: &[&str] = &[" an der "];

pub(super) static NAME_GERMAN_3_AM: &[&str] = &[" am "];

pub(super) static NAME_GERMAN_4_AN_DER: &[&str] = &["Oder", "Spree", "Donau", "Saale", "Elbe"];

pub(super) static NAME_GERMAN_4_AM: &[&str] = &["Main"];

pub(super) static NAME_SPANISH_REAL: &[&str] = &[
    "Caracas",
    "Maracay",
    "Maracaibo",
    "Valencia",
    "El Dorado",
    "Morrocoy",
    "Cata",
    "Cataito",
    "Ciudad Bol\u{00ed}var",
    "Barquisimeto",
    "M\u{00e9}rida",
    "Puerto Ordaz",
    "Santa Elena",
    "San Juan",
    "San Luis",
    "San Rafael",
    "Santiago",
    "Barcelona",
    "Barinas",
    "San Crist\u{00f3}bal",
    "San Francisco",
    "San Mart\u{00ed}n",
    "Guayana",
    "San Carlos",
    "El Lim\u{00f3}n",
    "Coro",
    "Coro Coro",
    "Puerto Ayacucho",
    "Elorza",
    "Arismendi",
    "Trujillo",
    "Car\u{00fa}pano",
    "Anaco",
    "Lima",
    "Cuzco",
    "Iquitos",
    "Callao",
    "Huacho",
    "Caman\u{00e1}",
    "Puerto Chala",
    "Santa Cruz",
    "Quito",
    "Cuenca",
    "Medell\u{00ed}n",
    "Tulc\u{00e1}n",
    "Esmeraldas",
    "Ibarra",
    "San Lorenzo",
    "Macas",
    "Mora\u{00f1}a",
    "Machala",
    "Zamora",
    "Latacunga",
    "Tena",
    "Cochabamba",
    "Ascensi\u{00f3}n",
    "Magdalena",
    "Santa Ana",
    "Manoa",
    "Sucre",
    "Oruro",
    "Uyuni",
    "Potos\u{00ed}",
    "Tupiza",
    "La Quiaca",
    "Yacu\u{00ed}ba",
    "San Borja",
    "Fuerte Olimpo",
    "Fort\u{00ed}n Esteros",
    "Campo Grande",
    "Bogot\u{00e1}",
    "El Banco",
    "Zaragoza",
    "Neiva",
    "Mariano",
    "Cali",
    "La Palma",
    "Andoas",
    "Barranca",
    "Montevideo",
    "Valdivia",
    "Arica",
    "Temuco",
    "Tocopilla",
    "Mendoza",
    "Santa Rosa",
];

pub(super) static NAME_FRENCH_REAL: &[&str] = &[
    "Agincourt",
    "Lille",
    "Dinan",
    "Aubusson",
    "Rodez",
    "Bergerac",
    "Bordeaux",
    "Bayonne",
    "Montpellier",
    "Mont\u{00e9}limar",
    "Valence",
    "Digne",
    "Nice",
    "Cannes",
    "St. Tropez",
    "Marseille",
    "Narbonne",
    "S\u{00e8}te",
    "Aurillac",
    "Gu\u{00e9}ret",
    "Le Creusot",
    "Nevers",
    "Auxerre",
    "Versailles",
    "Meaux",
    "Ch\u{00e2}lons",
    "Compi\u{00e8}gne",
    "Metz",
    "Chaumont",
    "Langres",
    "Bourg",
    "Lyon",
    "Vienne",
    "Grenoble",
    "Toulon",
    "Rennes",
    "Le Mans",
    "Angers",
    "Nantes",
    "Ch\u{00e2}teauroux",
    "Orl\u{00e9}ans",
    "Lisieux",
    "Cherbourg",
    "Morlaix",
    "Cognac",
    "Agen",
    "Tulle",
    "Blois",
    "Troyes",
    "Charolles",
    "Toulouse",
    "Chamb\u{00e9}ry",
    "Tours",
    "St. Brieuc",
    "St. Malo",
    "La Rochelle",
    "St. Flour",
    "Le Puy",
    "Vichy",
    "St. Valery",
    "Beaujolais",
    "Reims",
    "Albi",
    "Paris",
    "Biarritz",
    "B\u{00e9}ziers",
    "N\u{00ee}mes",
    "Chamonix",
    "Angoul\u{00e8}me",
    "Alen\u{00e7}on",
];

pub(super) static NAME_SILLY_1: &[&str] = &[
    "Binky", "Blubber", "Bumble", "Crinkle", "Crusty", "Dangle", "Dribble", "Flippety", "Google",
    "Muffin", "Nosey", "Pinker", "Quack", "Rumble", "Sleepy", "Sliggles", "Snooze", "Teddy",
    "Tinkle", "Twister", "Pinker", "Hippo", "Itchy", "Jelly", "Jingle", "Jolly", "Kipper", "Lazy",
    "Frogs", "Mouse", "Quack", "Cheeky", "Lumpy", "Grumpy", "Mangle", "Fiddle", "Slugs", "Noodles",
    "Poodles", "Shiver", "Rumble", "Pixie", "Puddle", "Riddle", "Rattle", "Rickety", "Waffle",
    "Sagging", "Sausage", "Egg", "Sleepy", "Scatter", "Scramble", "Silly", "Simple", "Trickle",
    "Slippery", "Slimey", "Slumber", "Soggy", "Sliggles", "Splutter", "Sulky", "Swindle", "Swivel",
    "Tasty", "Tangle", "Toggle", "Trotting", "Tumble", "Snooze", "Water", "Windy", "Amble",
    "Bubble", "Cheery", "Cheese", "Cockle", "Cracker", "Crumple", "Teddy", "Evil", "Fairy",
    "Falling", "Fishy", "Fizzle", "Frosty", "Griddle",
];

pub(super) static NAME_SILLY_2: &[&str] = &[
    "ton", "bury", "bottom", "ville", "well", "weed", "worth", "wig", "wick", "wood", "pool",
    "head", "burg", "gate", "bridge",
];

pub(super) static NAME_SWEDISH_1: &[&str] = &["Gamla ", "Lilla ", "Nya ", "Stora "];

pub(super) static NAME_SWEDISH_2: &[&str] = &[
    "Boll",
    "Bor",
    "Ed",
    "En",
    "Erik",
    "Es",
    "Fin",
    "Fisk",
    "Gr\u{00f6}n",
    "Hag",
    "Halm",
    "Karl",
    "Kram",
    "Kung",
    "Land",
    "Lid",
    "Lin",
    "Mal",
    "Malm",
    "Marie",
    "Ner",
    "Norr",
    "Oskar",
    "Sand",
    "Skog",
    "Stock",
    "Stor",
    "Str\u{00f6}m",
    "Sund",
    "S\u{00f6}der",
    "Tall",
    "Tratt",
    "Troll",
    "Upp",
    "Var",
    "V\u{00e4}ster",
    "\u{00c4}ngel",
    "\u{00d6}ster",
];

pub(super) static NAME_SWEDISH_2A: &[&str] = &[
    "B", "Br", "D", "Dr", "Dv", "F", "Fj", "Fl", "Fr", "G", "Gl", "Gn", "Gr", "H", "J", "K", "Kl",
    "Kn", "Kr", "Kv", "L", "M", "N", "P", "Pl", "Pr", "R", "S", "Sk", "Skr", "Sl", "Sn", "Sp",
    "Spr", "St", "Str", "Sv", "T", "Tr", "Tv", "V", "Vr",
];

pub(super) static NAME_SWEDISH_2B: &[&str] = &[
    "a", "e", "i", "o", "u", "y", "\u{00e5}", "\u{00e4}", "\u{00f6}",
];

pub(super) static NAME_SWEDISH_2C: &[&str] = &[
    "ck", "d", "dd", "g", "gg", "l", "ld", "m", "n", "nd", "ng", "nn", "p", "pp", "r", "rd", "rk",
    "rp", "rr", "rt", "s", "sk", "st", "t", "tt", "v",
];

pub(super) static NAME_SWEDISH_3: &[&str] = &[
    "arp",
    "berg",
    "boda",
    "borg",
    "bro",
    "bukten",
    "by",
    "byn",
    "fors",
    "hammar",
    "hamn",
    "holm",
    "hus",
    "h\u{00e4}ttan",
    "kulle",
    "k\u{00f6}ping",
    "lund",
    "l\u{00f6}v",
    "sala",
    "skrona",
    "sl\u{00e4}tt",
    "sp\u{00e5}ng",
    "stad",
    "sund",
    "svall",
    "svik",
    "s\u{00e5}ker",
    "udde",
    "valla",
    "viken",
    "\u{00e4}lv",
    "\u{00e5}s",
];

pub(super) static NAME_DUTCH_1: &[&str] = &[
    "Nieuw ", "Oud ", "Groot ", "Zuid ", "Noord ", "Oost ", "West ", "Klein ",
];

pub(super) static NAME_DUTCH_2: &[&str] = &[
    "Hoog", "Laag", "Zuider", "Zuid", "Ooster", "Oost", "Wester", "West", "Hoofd", "Midden",
    "Eind", "Amster", "Amstel", "Dord", "Rotter", "Haar", "Til", "Enk", "Dok", "Veen", "Leidsch",
    "Lely", "En", "Kaats", "U", "Maas", "Mar", "Bla", "Al", "Alk", "Eer", "Drie", "Ter", "Groes",
    "Goes", "Soest", "Coe", "Uit", "Zwaag", "Hellen", "Slie", "IJ", "Grubben", "Groen", "Lek",
    "Ridder", "Schie", "Olde", "Roose", "Haar", "Til", "Loos", "Hil",
];

pub(super) static NAME_DUTCH_3: &[&str] = &[
    "Drog", "Nat", "Valk", "Bob", "Dedem", "Kollum", "Best", "Hoend", "Leeuw", "Graaf", "Uithuis",
    "Purm", "Hard", "Hell", "Werk", "Spijk", "Vink", "Wams", "Heerhug", "Koning",
];

pub(super) static NAME_DUTCH_4: &[&str] = &["e", "er", "el", "en", "o", "s"];

pub(super) static NAME_DUTCH_5: &[&str] = &[
    "stad", "vorst", "dorp", "dam", "beek", "doorn", "zijl", "zijlen", "lo", "muiden", "meden",
    "vliet", "nisse", "daal", "vorden", "vaart", "mond", "zaal", "water", "duinen", "heuvel",
    "geest", "kerk", "meer", "maar", "hoorn", "rade", "wijk", "berg", "heim", "sum", "richt",
    "burg", "recht", "drecht", "trecht", "tricht", "dricht", "lum", "rum", "halen", "oever",
    "wolde", "veen", "hoven", "gast", "kum", "hage", "dijk", "zwaag", "pomp", "huizen", "bergen",
    "schede", "mere", "end",
];

pub(super) static NAME_FINNISH_REAL: &[&str] = &[
    "Aijala",
    "Kisko",
    "Espoo",
    "Helsinki",
    "Tapiola",
    "J\u{00e4}rvel\u{00e4}",
    "Lahti",
    "Kotka",
    "Hamina",
    "Loviisa",
    "Kouvola",
    "Tampere",
    "Oulu",
    "Salo",
    "Malmi",
    "Pelto",
    "Koski",
    "Iisalmi",
    "Raisio",
    "Taavetti",
    "Joensuu",
    "Imatra",
    "Tapanila",
    "Pasila",
    "Turku",
    "Kupittaa",
    "Vaasa",
    "Pori",
    "Rauma",
    "Kolari",
    "Lieksa",
];

pub(super) static NAME_FINNISH_1: &[&str] = &[
    "Hiekka",
    "Haapa",
    "Mylly",
    "Sauna",
    "Uusi",
    "Vanha",
    "Kes\u{00e4}",
    "Kuusi",
    "Pelto",
    "Tuomi",
    "Terva",
    "Olki",
    "Hein\u{00e4}",
    "Sein\u{00e4}",
    "Rova",
    "Koivu",
    "Kokko",
    "M\u{00e4}nty",
    "Pihlaja",
    "Pet\u{00e4}j\u{00e4}",
    "Kielo",
    "Kauha",
    "Viita",
    "Kivi",
    "Riihi",
    "\u{00c4}\u{00e4}ne",
    "Niini",
];

pub(super) static NAME_FINNISH_2: &[&str] = &[
    "Lappeen",
    "Lohjan",
    "Savon",
    "Lapin",
    "Pit\u{00e4}j\u{00e4}n",
    "Martin",
    "Kuusan",
    "Kemi",
    "Keri",
    "H\u{00e4}meen",
    "Kangas",
];

pub(super) static NAME_FINNISH_3: &[&str] = &[
    "harju",
    "linna",
    "j\u{00e4}rvi",
    "kallio",
    "m\u{00e4}ki",
    "nummi",
    "joki",
    "kyl\u{00e4}",
    "lampi",
    "lahti",
    "mets\u{00e4}",
    "suo",
    "laakso",
    "niitty",
    "luoto",
    "hovi",
    "ranta",
    "koski",
    "salo",
];

pub(super) static NAME_POLISH_1_M: &[&str] = &[
    "Wielki ",
    "Ma\u{0142}y ",
    "Z\u{0142}y ",
    "Dobry ",
    "Nowy ",
    "Stary ",
    "Z\u{0142}oty ",
    "Zielony ",
    "Bia\u{0142}y ",
    "Modry ",
    "D\u{0119}bowy ",
];

pub(super) static NAME_POLISH_1_F: &[&str] = &[
    "Wielka ",
    "Ma\u{0142}a ",
    "Z\u{0142}a ",
    "Dobra ",
    "Nowa ",
    "Stara ",
    "Z\u{0142}ota ",
    "Zielona ",
    "Bia\u{0142}a ",
    "Modra ",
    "D\u{0119}bowa ",
];

pub(super) static NAME_POLISH_1_N: &[&str] = &[
    "Wielkie ",
    "Ma\u{0142}e ",
    "Z\u{0142}e ",
    "Dobre ",
    "Nowe ",
    "Stare ",
    "Z\u{0142}ote ",
    "Zielone ",
    "Bia\u{0142}e ",
    "Modre ",
    "D\u{0119}bowe ",
];

pub(super) static NAME_POLISH_2_O: &[&str] = &[
    "Frombork",
    "Gniezno",
    "Olsztyn",
    "Toru\u{0144}",
    "Bydgoszcz",
    "Terespol",
    "Krak\u{00f3}w",
    "Pozna\u{0144}",
    "Wroc\u{0142}aw",
    "Katowice",
    "Cieszyn",
    "Bytom",
    "Frombork",
    "Hel",
    "Konin",
    "Lublin",
    "Malbork",
    "Sopot",
    "Sosnowiec",
    "Gda\u{0144}sk",
    "Gdynia",
    "Sieradz",
    "Sandomierz",
    "Szczyrk",
    "Szczytno",
    "Szczecin",
    "Zakopane",
    "Szklarska Por\u{0119}ba",
    "Bochnia",
    "Golub-Dobrzy\u{0144}",
    "Chojnice",
    "Ostrowiec",
    "Otwock",
    "Wolsztyn",
];

pub(super) static NAME_POLISH_2_M: &[&str] = &[
    "Jarocin",
    "Gogolin",
    "Tomasz\u{00f3}w",
    "Piotrk\u{00f3}w",
    "Lidzbark",
    "Rypin",
    "Radzymin",
    "Wo\u{0142}omin",
    "Pruszk\u{00f3}w",
    "Olsztynek",
    "Rypin",
    "Cisek",
    "Krotoszyn",
    "Stoczek",
    "Lubin",
    "Lubicz",
    "Milicz",
    "Targ",
    "Ostr\u{00f3}w",
    "Ozimek",
    "Puck",
    "Rzepin",
    "Siewierz",
    "Stargard",
    "Starogard",
    "Turek",
    "Tymbark",
    "Wolsztyn",
    "Strzepcz",
    "Strzebielin",
    "Sochaczew",
    "Gr\u{0119}bocin",
    "Gniew",
    "Lubliniec",
    "Lubasz",
    "Lutomiersk",
    "Niemodlin",
    "Przeworsk",
    "Ursus",
    "Tyczyn",
    "Sztum",
    "Szczebrzeszyn",
    "Wolin",
    "Wrzeszcz",
    "Zgierz",
    "Zieleniec",
    "Drobin",
    "Garwolin",
];

pub(super) static NAME_POLISH_2_F: &[&str] = &[
    "Szprotawa",
    "Pogorzelica",
    "Mot\u{0142}awa",
    "Lubawa",
    "Nidzica",
    "Kruszwica",
    "Bierawa",
    "Brodnica",
    "Chojna",
    "Krzepica",
    "Ruda",
    "Rumia",
    "Tuchola",
    "Trzebinia",
    "Ustka",
    "Warszawa",
    "Bobowa",
    "Dukla",
    "Krynica",
    "Murowana",
    "Niemcza",
    "Zaspa",
    "Zawoja",
    "Wola",
    "Limanowa",
    "Rabka",
    "Skawina",
    "Pilawa",
];

pub(super) static NAME_POLISH_2_N: &[&str] = &[
    "Lipsko",
    "Pilzno",
    "Przodkowo",
    "Strzelno",
    "Leszno",
    "Jaworzno",
    "Choszczno",
    "Mogilno",
    "Luzino",
    "Miasto",
    "Dziadowo",
    "Kowalewo",
    "Legionowo",
    "Miastko",
    "Zabrze",
    "Zawiercie",
    "Kochanowo",
    "Miechucino",
    "Mirachowo",
    "Robakowo",
    "Kosakowo",
    "Borne",
    "Braniewo",
    "Sulinowo",
    "Chmielno",
    "Jastrz\u{0119}bie",
    "Gryfino",
    "Koronowo",
    "Lubichowo",
    "Opoczno",
];

pub(super) static NAME_POLISH_3_M: &[&str] = &[
    " Wybudowanie",
    " \u{015a}wi\u{0119}tokrzyski",
    " G\u{00f3}rski",
    " Morski",
    " Zdr\u{00f3}j",
    " Wody",
    " Bajoro",
    " Kraje\u{0144}ski",
    " \u{015a}l\u{0105}ski",
    " Mazowiecki",
    " Pomorski",
    " Wielki",
    " Maly",
    " Warmi\u{0144}ski",
    " Mazurski",
    " Mniejszy",
    " Wi\u{0119}kszy",
    " G\u{00f3}rny",
    " Dolny",
    " Wielki",
    " Stary",
    " Nowy",
    " Wielkopolski",
    " Wzg\u{00f3}rze",
    " Mosty",
    " Kujawski",
    " Ma\u{0142}opolski",
    " Podlaski",
    " Lesny",
];

pub(super) static NAME_POLISH_3_F: &[&str] = &[
    " Wybudowanie",
    " \u{015a}wi\u{0119}tokrzyska",
    " G\u{00f3}rska",
    " Morska",
    " Zdr\u{00f3}j",
    " Woda",
    " Bajoro",
    " Kraje\u{0144}ska",
    " \u{015a}l\u{0105}ska",
    " Mazowiecka",
    " Pomorska",
    " Wielka",
    " Ma\u{0142}a",
    " Warmi\u{0144}ska",
    " Mazurska",
    " Mniejsza",
    " Wi\u{0119}ksza",
    " G\u{00f3}rna",
    " Dolna",
    " Wielka",
    " Stara",
    " Nowa",
    " Wielkopolska",
    " Wzg\u{00f3}rza",
    " Mosty",
    " Kujawska",
    " Malopolska",
    " Podlaska",
    " Le\u{015b}na",
];

pub(super) static NAME_POLISH_3_N: &[&str] = &[
    " Wybudowanie",
    " \u{015a}wietokrzyskie",
    " G\u{00f3}rskie",
    " Morskie",
    " Zdr\u{00f3}j",
    " Wody",
    " Bajoro",
    " Kraje\u{0144}skie",
    " \u{015a}l\u{0105}skie",
    " Mazowieckie",
    " Pomorskie",
    " Wielkie",
    " Ma\u{0142}e",
    " Warmi\u{0144}skie ",
    " Mazurskie ",
    " Mniejsze",
    " Wi\u{0119}ksze",
    " G\u{00f3}rne",
    " Dolne",
    " Wielkie",
    " Stare",
    " Nowe",
    " Wielkopolskie",
    " Wzg\u{00f3}rze",
    " Mosty",
    " Kujawskie",
    " Ma\u{0142}opolskie",
    " Podlaskie",
    " Le\u{015b}ne",
];

pub(super) static NAME_CZECH_REAL: &[&str] = &[
    "A\u{0161}",
    "Bene\u{0161}ov",
    "Beroun",
    "Bezdru\u{017e}ice",
    "Blansko",
    "B\u{0159}eclav",
    "Brno",
    "Brunt\u{00e1}l",
    "\u{010c}esk\u{00e1} L\u{00ed}pa",
    "\u{010c}esk\u{00e9} Bud\u{011b}jovice",
    "\u{010c}esk\u{00fd} Krumlov",
    "D\u{011b}\u{010d}\u{00ed}n",
    "Doma\u{017e}lice",
    "Dub\u{00ed}",
    "Fr\u{00fd}dek-M\u{00ed}stek",
    "Havl\u{00ed}\u{010d}k\u{016f}v Brod",
    "Hodon\u{00ed}n",
    "Hradec Kr\u{00e1}lov\u{00e9}",
    "Humpolec",
    "Cheb",
    "Chomutov",
    "Chrudim",
    "Jablonec nad Nisou",
    "Jesen\u{00ed}k",
    "Ji\u{010d}\u{00ed}n",
    "Jihlava",
    "Jind\u{0159}ich\u{016f}v Hradec",
    "Karlovy Vary",
    "Karvin\u{00e1}",
    "Kladno",
    "Klatovy",
    "Kol\u{00ed}n",
    "Kosmonosy",
    "Krom\u{011b}\u{0159}\u{00ed}\u{017e}",
    "Kutn\u{00e1} Hora",
    "Liberec",
    "Litom\u{011b}\u{0159}ice",
    "Louny",
    "Man\u{011b}t\u{00ed}n",
    "M\u{011b}ln\u{00ed}k",
    "Mlad\u{00e1} Boleslav",
    "Most",
    "N\u{00e1}chod",
    "Nov\u{00fd} Ji\u{010d}\u{00ed}n",
    "Nymburk",
    "Olomouc",
    "Opava",
    "Or\u{00e1}\u{010d}ov",
    "Ostrava",
    "Pardubice",
    "Pelh\u{0159}imov",
    "Pol\u{017e}ice",
    "P\u{00ed}sek",
    "Plze\u{0148}",
    "Praha",
    "Prachatice",
    "P\u{0159}erov",
    "P\u{0159}\u{00ed}bram",
    "Prost\u{011b}jov",
    "Rakovn\u{00ed}k",
    "Rokycany",
    "Rudn\u{00e1}",
    "Rychnov nad Kn\u{011b}\u{017e}nou",
    "Semily",
    "Sokolov",
    "Strakonice",
    "St\u{0159}edokluky",
    "\u{0160}umperk",
    "Svitavy",
    "T\u{00e1}bor",
    "Tachov",
    "Teplice",
    "T\u{0159}eb\u{00ed}\u{010d}",
    "Trutnov",
    "Uhersk\u{00e9} Hradi\u{0161}t\u{011b}",
    "\u{00da}st\u{00ed} nad Labem",
    "\u{00da}st\u{00ed} nad Orlic\u{00ed}",
    "Vset\u{00ed}n",
    "Vy\u{0161}kov",
    "\u{017d}\u{010f}\u{00e1}r nad S\u{00e1}zavou",
    "Zl\u{00ed}n",
    "Znojmo",
];

pub(super) static NAME_CZECH_SUBST_POSTFIX: &[&str] =
    &["av", "an", "at", "ov", "on", "ot", "ev", "en", "et"];

pub(super) static NAME_CZECH_SUFFIX: &[&str] = &[
    "nad Cidlinou",
    "nad Dyj\u{00ed}",
    "nad Jihlavou",
    "nad Labem",
    "nad Lesy",
    "nad Moravou",
    "nad Nisou",
    "nad Odrou",
    "nad Ostravic\u{00ed}",
    "nad S\u{00e1}zavou",
    "nad Vltavou",
    "pod Prad\u{011b}dem",
    "pod Radho\u{0161}t\u{011b}m",
    "pod \u{0158}\u{00ed}pem",
    "pod Sn\u{011b}\u{017e}kou",
    "pod \u{0160}pi\u{010d}\u{00e1}kem",
    "pod Sedlem",
    "v \u{010c}ech\u{00e1}ch",
    "na Morav\u{011b}",
];

pub(super) static NAME_ROMANIAN_REAL: &[&str] = &[
    "Adjud",
    "Alba Iulia",
    "Alexandria",
    "Babadag",
    "Bac\u{0103}u",
    "Baia Mare",
    "B\u{0103}ile Herculane",
    "B\u{0103}ile\u{0219}ti",
    "B\u{00e2}rlad",
    "Bicaz",
    "Bistri\u{021b}a",
    "Blaj",
    "Borsec",
    "Boto\u{0219}ani",
    "Br\u{0103}ila",
    "Bra\u{0219}ov",
    "Bucure\u{0219}ti",
    "Buftea",
    "Buz\u{0103}u",
    "C\u{0103}l\u{0103}ra\u{0219}i",
    "Caransebe\u{0219}",
    "Cernavod\u{0103}",
    "Cluj-Napoca",
    "Constan\u{021b}a",
    "Covasna",
    "Craiova",
    "Dej",
    "Deva",
    "Dorohoi",
    "Drobeta-Turnu Severin",
    "Dr\u{0103}g\u{0103}\u{0219}ani",
    "F\u{0103}g\u{0103}ra\u{0219}",
    "F\u{0103}lticeni",
    "Fete\u{0219}ti",
    "Foc\u{0219}ani",
    "Gala\u{021b}i",
    "Gheorgheni",
    "Giurgiu",
    "H\u{00e2}r\u{0219}ova",
    "Hunedoara",
    "Hu\u{0219}i",
    "Ia\u{0219}i",
    "Isaccea",
    "Lugoj",
    "M\u{0103}cin",
    "Mangalia",
    "Medgidia",
    "Media\u{0219}",
    "Miercurea Ciuc",
    "Mizil",
    "Motru",
    "N\u{0103}s\u{0103}ud",
    "N\u{0103}vodari",
    "Odobe\u{0219}ti",
    "Olteni\u{021b}a",
    "One\u{0219}ti",
    "Oradea",
    "Or\u{0219}ova",
    "Petro\u{0219}ani",
    "Piatra Neam\u{021b}",
    "Pite\u{0219}ti",
    "Ploie\u{0219}ti",
    "Predeal",
    "R\u{00e2}mnicu V\u{00e2}lcea",
    "Reghin",
    "Re\u{0219}i\u{021b}a",
    "Roman",
    "Ro\u{0219}iorii de Vede",
    "Satu Mare",
    "Sebe\u{0219}",
    "Sf\u{00e2}ntu Gheorghe",
    "Sibiu",
    "Sighi\u{0219}oara",
    "Sinaia",
    "Slatina",
    "Slobozia",
    "Sovata",
    "Suceava",
    "Sulina",
    "\u{021a}\u{0103}nd\u{0103}rei",
    "T\u{00e2}rgovi\u{0219}te",
    "T\u{00e2}rgu Jiu",
    "T\u{00e2}rgu Mure\u{0219}",
    "Tecuci",
    "Timi\u{0219}oara",
    "Tulcea",
    "Turda",
    "Turnu M\u{0103}gurele",
    "Urziceni",
    "Vaslui",
    "Vatra Dornei",
    "Victoria",
    "Videle",
    "Zal\u{0103}u",
];

pub(super) static NAME_SLOVAK_REAL: &[&str] = &[
    "Bratislava",
    "B\u{00e1}novce nad Bebravou",
    "Bansk\u{00e1} Bystrica",
    "Bansk\u{00e1} \u{0160}tiavnica",
    "Bardejov",
    "Brezno",
    "Brezova pod Bradlom",
    "Byt\u{010d}a",
    "\u{010c}adca",
    "\u{010c}ierna nad Tisou",
    "Detva",
    "Pre\u{0161}ov",
    "Dolny Kubin",
    "Spi\u{0161}sk\u{00e1} Nov\u{00e1} Ves",
    "Dunajsk\u{00e1} Streda",
    "Gab\u{010d}\u{00ed}ikovo",
    "Galanta",
    "Gbely",
    "Gelnica",
    "Handlov\u{00e1}",
    "Hlohovec",
    "Hol\u{00ed}\u{010d}",
    "Humenn\u{00e9}",
    "Hurbanovo",
    "Kezmarok",
    "Kom\u{00e1}rno",
    "Ko\u{0161}ice",
    "Kremnica",
    "Krompachy",
    "Kuty",
    "Leopoldov",
    "Levo\u{010d}a",
    "Liptovsk\u{00fd} Mikul\u{00e1}\u{0161}",
    "Lu\u{010d}enec",
    "Malacky",
    "Martin",
    "Medzilaborce",
    "Michalovce",
    "Modra",
    "Myjava",
    "N\u{00e1}mestovo",
    "Nitra",
    "Nov\u{00e1} Ba\u{0148}a",
    "Nov\u{00e9} Mesto nad V\u{00e1}hom",
    "Nov\u{00e9} Z\u{00e1}mky",
    "Partiz\u{00e1}nske",
    "Pezinok",
    "Pie\u{0161}\u{0165}any",
    "Polt\u{00e1}r",
    "Poprad",
    "Pova\u{017e}sk\u{00e1} Bystrica",
    "Prievidza",
    "P\u{00fa}chov",
    "Rev\u{00fa}ca",
    "Rimavsk\u{00e1} Sobota",
    "Ro\u{017e}\u{0148}ava",
    "Ru\u{017e}omberok",
    "Sabinov",
    "\u{0160}a\u{013e}a",
    "Senec",
    "Senica",
    "Sere\u{010f}",
    "Skalica",
    "Sl\u{00e1}dkovi\u{00cd}ovo",
    "Smolenice",
    "Snina",
    "Star\u{00e1} \u{013d}ubov\u{0148}a",
    "Star\u{00e1} Tur\u{00e1}",
    "Str\u{00e1}\u{017e}ske",
    "Stropkov",
    "Stupava",
    "\u{0160}t\u{00fa}rovo",
    "\u{0120}ulekovo",
    "Topo\u{013e}\u{010d}any",
    "Trebi\u{0161}ov",
    "Tren\u{010d}\u{00ed}n",
    "Trnava",
    "Tur\u{010d}ianske Teplice",
    "Tvrdo\u{0161}\u{00ed}n",
    "Vr\u{00e1}ble",
    "Vranov nad Top\u{013e}ou",
    "Z\u{00e1}horsk\u{00e1} Bystrica",
    "\u{017d}diar",
    "\u{013d}iar nad Hronom",
    "\u{017d}ilina",
    "Zlat\u{00e9} Moravce",
    "Zvolen",
];

pub(super) static NAME_NORWEGIAN_1: &[&str] = &[
    "Arna",
    "Aust",
    "Bj\u{00f8}rk",
    "Bj\u{00f8}rn",
    "Brand",
    "B\u{00f8}ver",
    "Drag",
    "Dr\u{00f8}",
    "Eids",
    "Egge",
    "Fager",
    "Finns",
    "Flat",
    "Foll",
    "Foss",
    "Fugle",
    "Furu",
    "Gaus",
    "Galte",
    "Geir",
    "Gl\u{00f8}s",
    "Gran",
    "Grind",
    "Grims",
    "Gr\u{00f8}n",
    "Gr\u{00f8}t",
    "Gulle",
    "Haka",
    "Hammer",
    "Haug",
    "Hol",
    "Hon",
    "Hop",
    "Hov",
    "Jess",
    "Kabel",
    "Kjerns",
    "Kjerring",
    "Knatte",
    "Krok",
    "K\u{00f8}y",
    "Lang",
    "Lauv",
    "Leir",
    "Lund",
    "Logn",
    "Lo",
    "Lyng",
    "L\u{00f8}n",
    "Mesna",
    "Mel",
    "Mo",
    "Nar",
    "Nitte",
    "Nord",
    "Odd",
    "Ola",
    "Otte",
    "Ran",
    "Rev",
    "Rog",
    "Roms",
    "Rosen",
    "Sand",
    "Sau",
    "Sel",
    "Sol",
    "Sjur",
    "Sk\u{00e5}r",
    "Sl\u{00e5}tt",
    "Stj\u{00f8}r",
    "Stor",
    "Svart",
    "Svens",
    "Svin",
    "Sylte",
    "Syn",
    "Tran",
    "Vass",
    "Ved",
    "Vest",
    "Vesle",
    "Vik",
    "V\u{00e5}g",
];

pub(super) static NAME_NORWEGIAN_2: &[&str] = &[
    "aker",
    "anger",
    "bakken",
    "bekk",
    "berg",
    "botn",
    "breen",
    "bu",
    "bugen",
    "by",
    "bygd",
    "b\u{00f8}",
    "dal",
    "egga",
    "eid",
    "elv",
    "enga",
    "foss",
    "fjell",
    "fjord",
    "foten",
    "gard",
    "grend",
    "hammer",
    "haug",
    "havn",
    "heim",
    "hella",
    "hovda",
    "h\u{00f8}a",
    "h\u{00f8}gda",
    "kampen",
    "kj\u{00f8}len",
    "kollen",
    "kroken",
    "land",
    "lia",
    "mark",
    "moen",
    "myr",
    "nes",
    "nuten",
    "osen",
    "rike",
    "rud",
    "sand",
    "set",
    "sj\u{00f8}en",
    "skogen",
    "slette",
    "snipa",
    "stad",
    "stua",
    "stulen",
    "sund",
    "svingen",
    "s\u{00e6}tra",
    "tinden",
    "tun",
    "vang",
    "vatn",
    "veid",
    "vik",
    "voll",
    "v\u{00e5}g",
    "um",
    "\u{00e5}sen",
];

pub(super) static NAME_NORWEGIAN_REAL: &[&str] = &[
    "Alta",
    "Arendal",
    "Askim",
    "Bergen",
    "Bod\u{00f8}",
    "Brevik",
    "Bryne",
    "Br\u{00f8}nn\u{00f8}ysund",
    "Drammen",
    "Dr\u{00f8}bak",
    "Egersund",
    "Elverum",
    "Farsund",
    "Fauske",
    "Finnsnes",
    "Flekkefjord",
    "Flora",
    "Fosnav\u{00e5}g",
    "Fredrikstad",
    "F\u{00f8}rde",
    "Gj\u{00f8}vik",
    "Grimstad",
    "Halden",
    "Hamar",
    "Hammerfest",
    "Harstad",
    "Haugesund",
    "Holmestrand",
    "Horten",
    "J\u{00f8}rpeland",
    "Kirkenes",
    "Kolvereid",
    "Kongsberg",
    "Kongsvinger",
    "Kopervik",
    "Krager\u{00f8}",
    "Kristiansand",
    "Kristiansund",
    "Langesund",
    "Larvik",
    "Leirvik",
    "Leknes",
    "Levanger",
    "Lillehammer",
    "Lillesand",
    "Lillestr\u{00f8}m",
    "Lyngdal",
    "L\u{00f8}renskog",
    "Mandal",
    "Mo i Rana",
    "Molde",
    "Mosj\u{00f8}en",
    "Moss",
    "Mysen",
    "M\u{00e5}l\u{00f8}y",
    "Namsos",
    "Narvik",
    "Notodden",
    "Odda",
    "Oslo",
    "Otta",
    "Porsgrunn",
    "Ringerike",
    "Ris\u{00f8}r",
    "Rjukan",
    "Sandefjord",
    "Sandnes",
    "Sandnessj\u{00f8}en",
    "Sandvika",
    "Sarpsborg",
    "Sauda",
    "Ski",
    "Skien",
    "Skudeneshavn",
    "Sortland",
    "Stathelle",
    "Stavanger",
    "Steinkjer",
    "Stj\u{00f8}rdal",
    "Stokmarknes",
    "Stord",
    "Svelvik",
    "Svolv\u{00e6}r",
    "Troms\u{00f8}",
    "Trondheim",
    "Tvedestrand",
    "T\u{00f8}nsberg",
    "Ulsteinvik",
    "Vads\u{00f8}",
    "Vard\u{00f8}",
    "Verdals\u{00f8}ra",
    "\u{00c5}krehamn",
    "\u{00c5}lesund",
    "\u{00c5}ndalsnes",
];

pub(super) static NAME_HUNGARIAN_1: &[&str] = &[
    "Nagy-",
    "Kis-",
    "Fels\u{0151}-",
    "Als\u{00f3}-",
    "\u{00da}j-",
];

pub(super) static NAME_HUNGARIAN_2: &[&str] = &[
    "Bodrog",
    "Dr\u{00e1}va",
    "Duna",
    "Hej\u{0151}",
    "Hern\u{00e1}d",
    "R\u{00e1}ba",
    "Saj\u{00f3}",
    "Szamos",
    "Tisza",
    "Zala",
    "Balaton",
    "Fert\u{0151}",
    "Bakony",
    "Cserh\u{00e1}t",
    "Bihar",
    "Hajd\u{00fa}",
    "J\u{00e1}sz",
    "Kun",
    "Magyar",
    "N\u{00f3}gr\u{00e1}d",
    "Ny\u{00ed}r",
    "Somogy",
    "Sz\u{00e9}kely",
    "Buda",
    "Gy\u{0151}r",
    "Pest",
    "Feh\u{00e9}r",
    "Cser\u{00e9}p",
    "Erd\u{0151}",
    "Hegy",
    "Homok",
    "Mez\u{0151}",
    "Puszta",
    "S\u{00e1}r",
    "Cs\u{00e1}sz\u{00e1}r",
    "Herceg",
    "Kir\u{00e1}ly",
    "Nemes",
    "P\u{00fc}sp\u{00f6}k",
    "Szent",
    "Alm\u{00e1}s",
    "Szilv\u{00e1}s",
    "Agg",
    "Aranyos",
    "B\u{00e9}k\u{00e9}s",
    "Egyh\u{00e1}zas",
    "Gagy",
    "Heves",
    "Kapos",
    "T\u{00e1}pi\u{00f3}",
    "Torna",
    "Vas",
    "V\u{00e1}mos",
    "V\u{00e1}s\u{00e1}ros",
];

pub(super) static NAME_HUNGARIAN_3: &[&str] = &[
    "ap\u{00e1}ti",
    "b\u{00e1}ba",
    "bikk",
    "dob",
    "fa",
    "f\u{00f6}ld",
    "hegyes",
    "kak",
    "kereszt",
    "k\u{00fc}rt",
    "lad\u{00e1}ny",
    "m\u{00e9}rges",
    "szalonta",
    "telek",
    "vas",
    "v\u{00f6}lgy",
];

pub(super) static NAME_HUNGARIAN_4: &[&str] = &[
    "alja",
    "egyh\u{00e1}za",
    "h\u{00e1}za",
    "\u{00fa}r",
    "v\u{00e1}r",
];

pub(super) static NAME_HUNGARIAN_REAL: &[&str] = &[
    "Ajka",
    "Asz\u{00f3}d",
    "Badacsony",
    "Baja",
    "Budapest",
    "Debrecen",
    "Eger",
    "Fony\u{00f3}d",
    "G\u{00f6}d\u{00f6}ll\u{0151}",
    "Gy\u{0151}r",
    "Gyula",
    "Karcag",
    "Kecskem\u{00e9}t",
    "Keszthely",
    "Kisk\u{00f6}re",
    "Kocsord",
    "Kom\u{00e1}rom",
    "K\u{0151}szeg",
    "Mak\u{00f3}",
    "Moh\u{00e1}cs",
    "Miskolc",
    "\u{00d3}zd",
    "Paks",
    "P\u{00e1}pa",
    "P\u{00e9}cs",
    "Polg\u{00e1}r",
    "Sarkad",
    "Si\u{00f3}fok",
    "Szeged",
    "Szentes",
    "Szolnok",
    "Tihany",
    "Tokaj",
    "V\u{00e1}c",
    "Z\u{00e1}hony",
    "Zirc",
];

pub(super) static NAME_SWISS_REAL: &[&str] = &[
    "Aarau",
    "Aesch",
    "Altdorf",
    "Arosa",
    "Appenzell",
    "Arbon",
    "Altst\u{00e4}tten",
    "Baar",
    "Baden",
    "Bellinzona",
    "Brig-Glis",
    "Bienne",
    "Bulle",
    "Binningen",
    "Burgdorf",
    "Bern",
    "Basel",
    "B\u{00fc}lach",
    "Carouge",
    "Cham",
    "Chiasso",
    "Chur",
    "Davos",
    "Del\u{00e9}mont",
    "Dietikon",
    "D\u{00fc}bendorf",
    "Emmen",
    "Freienbach-Pf\u{00e4}ffikon",
    "Fribourg",
    "Frauenfeld",
    "Gen\u{00e8}ve",
    "Glarus",
    "Gossau",
    "Grenchen",
    "Herisau",
    "Horgen",
    "Horw",
    "Illnau-Effretikon",
    "Ittigen",
    "Jona",
    "Kriens",
    "Kloten",
    "K\u{00f6}niz",
    "Kreuzlingen",
    "K\u{00fc}snacht",
    "Agen",
    "Lancy",
    "La Chaux-de-Fonds",
    "Lenzburg",
    "Lugano",
    "Langenthal",
    "Littau",
    "Le Locle",
    "La Neuveville",
    "Locarno",
    "Liestal",
    "La Tour-de-Peilz",
    "Lausanne",
    "Lyss",
    "Luzern",
    "Martigny",
    "M\u{00fc}nchenstein",
    "Meyrin",
    "Montreux",
    "Monthey",
    "Morges",
    "Murten",
    "Moutier",
    "Muttenz",
    "Neuch\u{00e2}tel",
    "Neuhausen am Rheinfall",
    "Nyon",
    "Olten",
    "Onex",
    "Opfikon",
    "Ostermundigen",
    "Payerne",
    "Peseux",
    "Prilly",
    "Pully",
    "Rapperswil",
    "Richterswil",
    "Regensdorf",
    "Rheinfelden",
    "Riehen",
    "Renens",
    "Romanshorn",
    "Rorschach",
    "Stans",
    "Schaffhausen",
    "Steffisburg",
    "St. Gallen",
    "Schlieren",
    "Sierre",
    "Solothurn",
    "St. Moritz",
    "Sion",
    "Spiez",
    "St\u{00e4}fa",
    "Sursee",
    "Schwyz",
    "Thalwil",
    "Th\u{00f4}nex",
    "Thun",
    "Uster",
    "Uzwil",
    "Vernier",
    "Volketswil",
    "Versoix",
    "Vevey",
    "W\u{00e4}denswil",
    "Wettingen",
    "Wil",
    "Wallisellen",
    "Winterthur",
    "Wohlen",
    "Worb",
    "Wetzikon",
    "Yverdon-les-Bains",
    "Zollikon",
    "Zofingen",
    "Z\u{00fc}rich",
    "Zug",
];

pub(super) static NAME_DANISH_1: &[&str] = &[
    "Gamle ",
    "Lille ",
    "Nye ",
    "Store ",
    "Kirke ",
    "N\u{00f8}rre ",
    "Vester ",
    "S\u{00f8}nder ",
    "\u{00d8}ster ",
    "Hvide ",
    "H\u{00f8}je ",
    "Kongens ",
];

pub(super) static NAME_DANISH_2: &[&str] = &[
    "Ager",
    "Alle",
    "Aske",
    "Balle",
    "Bede",
    "Birke",
    "Bjerring",
    "Bj\u{00e6}ver",
    "Blommens",
    "Blok",
    "Bolder",
    "Bred",
    "Charlotten",
    "Christians",
    "Danne",
    "Diana",
    "Es",
    "Fredens",
    "Frederiks",
    "Fugle",
    "F\u{00e5}re",
    "Gille",
    "Gis",
    "Givs",
    "Glams",
    "Glo",
    "Guld",
    "Had",
    "Haralds",
    "Hassel",
    "Hede",
    "Helle",
    "Hessel",
    "Hjorts",
    "Hol",
    "Horn",
    "Humle",
    "H\u{00f8}j",
    "H\u{00f8}r",
    "Is",
    "Jyde",
    "J\u{00e6}gers",
    "Karls",
    "Klov",
    "Kokke",
    "Kvist",
    "Lang",
    "Lange",
    "Mari",
    "Nord",
    "Ny",
    "Oks",
    "Ring",
    "R\u{00f8}de",
    "Rung",
    "R\u{00f8}r",
    "Rud",
    "Saks",
    "Salt",
    "Skam",
    "Silke",
    "Skod",
    "Sk\u{00e6}l",
    "Sk\u{00e6}r",
    "Sol",
    "Svend",
    "Svine",
    "Strand",
    "Stubbe",
    "Ting",
    "Tj\u{00e6}re",
    "Tore",
    "Uger",
    "Ulf",
    "Val",
    "Vand",
    "Vej",
    "Vor",
    "V\u{00e6}r",
    "\u{00d8}r",
    "\u{00c5}l",
];

pub(super) static NAME_DANISH_3: &[&str] = &[
    "basse",
    "borg",
    "berg",
    "bro",
    "by",
    "havn",
    "strup",
    "holm",
    "hus",
    "k\u{00f8}bing",
    "lund",
    "lunde",
    "sund",
    "ovre",
    "h\u{00f8}j",
    "dal",
    "sted",
    "sten",
    "l\u{00f8}se",
    "r\u{00f8}d",
    "magle",
    "s\u{00f8}",
    "bjerg",
    "b\u{00e6}k",
    "drup",
    "lev",
    "bo",
    "lyst",
    "feld",
    "skov",
];

pub(super) static NAME_TURKISH_PREFIX: &[&str] = &[
    "Ak\u{00e7}a",
    "Alt\u{0131}n",
    "Bah\u{00e7}e",
    "Boz",
    "B\u{00fc}y\u{00fc}k",
    "\u{00c7}ay",
    "Do\u{011f}u",
    "Eski",
    "G\u{00fc}zel",
    "K\u{0131}z\u{0131}l",
    "K\u{00fc}\u{00e7}\u{00fc}k",
    "Orta",
    "Sar\u{0131}",
    "Sultan",
    "Ulu",
    "Yeni",
];

pub(super) static NAME_TURKISH_MIDDLE: &[&str] = &[
    "aga\u{00e7}",
    "ayva",
    "\u{00e7}am",
    "elma",
    "kurt",
    "pazar",
    "yal\u{0131}",
];

pub(super) static NAME_TURKISH_SUFFIX: &[&str] = &[
    "dere",
    "hisar",
    "kale",
    "kaya",
    "kent",
    "k\u{00f6}y",
    "ova",
    "\u{00f6}z\u{00fc}",
    "\u{00f6}ren",
    "pazar",
    "saray",
    "tepe",
    "yer",
    "yurt",
];

pub(super) static NAME_TURKISH_REAL: &[&str] = &[
    "Adana",
    "Ad\u{0131}yaman",
    "Afyon",
    "A\u{011f}r\u{0131}",
    "Amasya",
    "Antalya",
    "Artvin",
    "Bal\u{0131}kesir",
    "Bilecik",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "\u{00c7}anakkale",
    "\u{00c7}ank\u{0131}r\u{0131}",
    "Denizli",
    "Diyarbak\u{0131}r",
    "Edirne",
    "Elaz\u{0131}\u{011f}",
    "Erzurum",
    "Eski\u{015f}ehir",
    "Giresun",
    "G\u{00fc}m\u{00fc}\u{015f}hane",
    "Hatay",
    "Isparta",
    "\u{0130}\u{00e7}el",
    "\u{0130}stanbul",
    "\u{0130}zmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kirklareli",
    "Kocaeli",
    "Konya",
    "K\u{00fc}tahya",
    "Malatya",
    "Manisa",
    "Kahramanmara\u{015f}",
    "Mardin",
    "Mu\u{011f}la",
    "Mu\u{015f}",
    "Nev\u{015f}ehir",
    "Ni\u{011f}de",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Trabzon",
    "\u{015e}anl\u{0131}urfa",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "\u{015e}\u{0131}rnak",
    "Bart\u{0131}n",
    "Ardahan",
    "I\u{011f}d\u{0131}r",
    "Yalova",
    "Karab\u{00fc}k",
    "Osmaniye",
    "D\u{00fc}zce",
];

pub(super) static NAME_ITALIAN_REAL: &[&str] = &[
    "Roma",
    "Milano",
    "Napoli",
    "Torino",
    "Venezia",
    "Firenze",
    "Palermo",
    "Genova",
    "Parma",
    "Bologna",
    "Bari",
    "Cagliari",
    "Sassari",
    "Pisa",
    "Aosta",
    "Brescia",
    "Verona",
    "Bolzano",
    "Padova",
    "Udine",
    "Trieste",
    "Livorno",
    "Ancona",
    "Perugia",
    "Pescara",
    "L'Aquila",
    "Campobasso",
    "Potenza",
    "Cosenza",
    "Reggio Calabria",
    "Catania",
    "Caltanisetta",
    "Agrigento",
    "La Spezia",
    "Modena",
    "Vicenza",
    "Mantova",
    "Cremona",
    "Piacenza",
    "Reggio Emilia",
    "Foggia",
    "Benevento",
    "Salerno",
    "Catanzaro",
    "Lecce",
    "Como",
    "Lecco",
    "Sondrio",
    "Trento",
    "Desenzano",
    "Cuneo",
    "Asti",
    "Lodi",
    "Novara",
    "Biella",
    "Vercelli",
    "Rieti",
    "Nuoro",
    "Oristano",
    "Matera",
    "Taranto",
    "Varese",
    "Bergamo",
    "Pavia",
    "Caserta",
    "Frosinone",
    "Latina",
    "Enna",
    "Ragusa",
    "Siracusa",
    "Pordenone",
    "Imperia",
    "Verbania",
    "Alessandria",
    "Messina",
    "Siena",
    "Arezzo",
    "Grosseto",
];

pub(super) static NAME_ITALIAN_PREF: &[&str] = &[
    "Alpe ", "Borgo ", "Cascina ", "Castel ", "Fonte ", "Forte ", "Malga ", "Pieve ", "Poggio ",
    "Rocca ", "Villa ", "Villar ",
];

pub(super) static NAME_ITALIAN_1M: &[&str] = &[
    "Bel", "Borgo", "Bosco", "Campo", "Capo", "Casal", "Castel", "Colle", "Fiume", "Fonte", "Lago",
    "Mezzo", "Monte", "Mon", "Orto", "Passo", "Prato", "Poggio", "Ponte", "Pozzo", "Sasso", "Tra",
    "Tre", "Ver", "Vico",
];

pub(super) static NAME_ITALIAN_1F: &[&str] = &[
    "Acqua", "Bra", "Cala", "Casa", "Chiesa", "Citta", "Civita", "Corte", "Costa", "Croce",
    "Fontana", "Grotta", "Guardia", "Mezza", "Palma", "Pietra", "Ripa", "Rocca", "Serra", "Torre",
    "Val", "Valle", "Villa",
];

pub(super) static NAME_ITALIAN_2: &[&str] = &[
    "bell", "bianc", "cald", "chiar", "cort", "ferrat", "fier", "fredd", "gioios", "grec", "guzz",
    "lung", "long", "migli", "negr", "ner", "nov", "nuov", "ross", "rotond", "scur", "secc",
    "sett", "vecchi", "ventos", "vers", "viv",
];

pub(super) static NAME_ITALIAN_2I: &[&str] = &[
    "", "breve", "brevi", "chiari", "ferro", "fieschi", "fiore", "fonte", "forte", "gate", "leone",
    "maggiore", "minore", "mole", "monte", "poli", "scuri", "terra", "te", "torrione", "vento",
    "verde", "versiere",
];

pub(super) static NAME_ITALIAN_3: &[&str] = &[
    " Marittimo",
    " Marittima",
    " del Capo",
    " del Monte",
    " di Sopra",
    " di Sotto",
    " sui Monti",
    " dei Marmi",
    " dei Sassi",
    " delle Fonti",
    " sui Prati",
    " a Mare",
    " Superiore",
    " Inferiore",
    " Terme",
    " Alta",
    " Bassa",
    " Brianza",
    " Vesuviano",
    " Scrivia",
    " Ticino",
];

pub(super) static NAME_ITALIAN_RIVER1: &[&str] = &[" del", " sul", " al", " nel"];

pub(super) static NAME_ITALIAN_RIVER2: &[&str] = &[
    "l'Adda",
    "l'Adige",
    "le Alpi",
    "l'Arno",
    " Bormida",
    " Brenta",
    "la Dora Baltea",
    " Lambro",
    " Mincio",
    " Naviglio",
    "l'Oglio",
    "l'Olona",
    "l'Ombrone",
    " Panaro",
    " Piave",
    " Po",
    " Reno",
    " Scrivia",
    " Secchia",
    " Serio",
    " Tagliamento",
    " Tanaro",
    " Taro",
    " Ticino",
    " Tevere",
];

pub(super) static NAME_CATALAN_REAL: &[&str] = &[
    "Barcelona",
    "L'Hospitalet de Llobregat",
    "Cerdanyola",
    "Martorell",
    "Badalona",
    "Tarragona",
    "Lleida",
    "Girona",
    "Sabadell",
    "Terrassa",
    "Reus",
    "Valls",
    "Vic",
    "Vielha e Mijaran",
    "Amposta",
    "Tortosa",
    "Berga",
    "Olot",
    "Mollerussa",
    "Banyoles",
    "Figueres",
    "Balaguer",
    "Vilafranca del Pened\u{00e8}s",
    "La Seu d'Urgell",
    "El Pont de Suert",
    "Igualada",
    "Manresa",
    "Solsona",
    "Les Borges Blanques",
    "Tremp",
    "Sort",
    "Colera",
    "Portbou",
    "El Vendrell",
    "Falset",
    "Ripoll",
    "Cervera",
    "Gandesa",
    "Matar\u{00f3}",
    "Montblanc",
    "Vilanova i la Geltr\u{00fa}",
    "T\u{00e0}rrega",
    "Camprodon",
    "Campdev\u{00e0}nol",
    "Cambrils",
    "Begur",
    "Setcases",
    "Palafrugell",
    "Begues",
    "El Bruc",
    "Cadaqu\u{00e9}s",
    "Collbat\u{00f3}",
    "Cervell\u{00f3}",
    "Esparreguera",
    "Abrera",
    "Alp",
    "Das",
    "Cercs",
    "Manlleu",
    "El Masnou",
    "Molins de Rei",
    "Monistrol",
    "Rocallaura",
    "Rub\u{00ed}",
    "Ripollet",
    "Sitges",
    "Roses",
];

pub(super) static NAME_CATALAN_PREF: &[&str] = &[
    "El Pont de ",
    "Parets de ",
    "Canet de ",
    "Castellar de ",
    "Corbera de ",
    "Arenys de ",
    "Calella de ",
    "La Seu de ",
    "La Bisbal de ",
    "Torroella de ",
    "Port de ",
    "Vilafranca de ",
    "Vilanova de ",
    "Caldes de ",
    "La Conca de ",
    "Olesa de ",
    "La Roca de ",
    "Sant Esteve de ",
    "Sant Andreu de ",
    "Sant Jordi de ",
    "Sant Joan de ",
    "Sant Feliu de ",
    "Sant Quirze de ",
    "Sant Sadurn\u{00ed} de ",
    "Santa Coloma de ",
    "Santa Margarida de ",
    "Santa Maria de ",
    "Sant Mart\u{00ed} de ",
    "Sant Pere de ",
    "Sant Juli\u{00e0} de ",
    "Sant Vicen\u{00e7} de ",
];

pub(super) static NAME_CATALAN_1M: &[&str] = &["Torrent", "Cami", "Mont", "Bell", "Puig", "Riu"];

pub(super) static NAME_CATALAN_1F: &[&str] = &[
    "Pala", "Selva", "Vall", "Serra", "Torre", "Riba", "Cova", "Terra",
];

pub(super) static NAME_CATALAN_2M: &[&str] = &[
    "alt",
    "baix",
    "fosc",
    "pelat",
    "vent\u{00f3}s",
    "negre",
    "roig",
    "gr\u{00ed}s",
];

pub(super) static NAME_CATALAN_2F: &[&str] = &[
    "baixa", "alta", "fosca", "clara", "negra", "roja", "grisa", "freda",
];

pub(super) static NAME_CATALAN_3: &[&str] = &[
    " Desp\u{00ed}",
    " Desvern",
    " del Cam\u{00ed}",
    " de Mar",
    " de Dalt",
    " de Baix",
    " del Vall\u{00e8}s",
    " de Bergued\u{00e0}",
    " de Conflent",
    " de la Plana",
];

pub(super) static NAME_CATALAN_RIVER1: &[&str] = &[
    " d'Anoia",
    " de Ter",
    " de Llobregat",
    " d'Ebre",
    " de Segre",
    " de Francol\u{00ed}",
];

pub(super) static NAME_CZECH_PATMOD: [[&str; 3]; 6] = [
    ["\u{00ed}", "\u{00fd}", "uv"],
    ["\u{00ed}", "\u{00e1}", "ova"],
    ["\u{00ed}", "\u{00e9}", "ovo"],
    ["\u{00ed}", "\u{00e9}", "ovy"],
    ["\u{00ed}", "\u{00e9}", "ovy"],
    ["\u{00ed}", "\u{00e1}", "ova"],
];

pub(super) static NAME_CZECH_ADJ: &[CzechNameAdj] = &[
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Horn",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Horn",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Doln",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Doln",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "P\u{0159}edn",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Zadn",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Kosteln",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Havran",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "\u{0158}\u{00ed}\u{010d}n",
    },
    CzechNameAdj {
        pattern: 0,
        choose: 7,
        name: "Jezern",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Velk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Velk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Mal",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Mal",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Vysok",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "\u{010c}esk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Moravsk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Slov\u{00e1}ck",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Slezsk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Uhersk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Star",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Star",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Nov",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Nov",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Mlad",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Kr\u{00e1}lovsk",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Kamenn",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Cihlov",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 7,
        name: "Divn",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{010c}erven",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{010c}erven",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{010c}erven",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "Zelen",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{017d}lut",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "Siv",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{0160}ed",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "B\u{00ed}l",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "B\u{00ed}l",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "Modr",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "R\u{016f}\u{017e}ov",
    },
    CzechNameAdj {
        pattern: 1,
        choose: 1,
        name: "\u{010c}ern",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Kr\u{00e1}l",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Jan",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Karl",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Kry\u{0161}tof",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Ji\u{0159}\u{00ed}k",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Petr",
    },
    CzechNameAdj {
        pattern: 2,
        choose: 7,
        name: "Sud",
    },
];

pub(super) static NAME_CZECH_SUBST_FULL: &[CzechNameSubst] = &[
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 1,
        name: "Sedlec",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 1,
        name: "Brod",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 1,
        name: "Brod",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 0,
        name: "\u{00da}val",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 1,
        name: "\u{017d}\u{010f}\u{00e1}r",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 1,
        name: "Smrk",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 7,
        choose: 1,
        name: "Hora",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 7,
        choose: 1,
        name: "Lhota",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 7,
        choose: 1,
        name: "Lhota",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 7,
        choose: 1,
        name: "Hlava",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 7,
        choose: 1,
        name: "L\u{00ed}pa",
    },
    CzechNameSubst {
        gender: CzechGender::SNeut,
        allow: 7,
        choose: 1,
        name: "Pole",
    },
    CzechNameSubst {
        gender: CzechGender::SNeut,
        allow: 7,
        choose: 1,
        name: "\u{00da}dol\u{00ed}",
    },
    CzechNameSubst {
        gender: CzechGender::PMasc,
        allow: 7,
        choose: 0,
        name: "\u{00da}valy",
    },
    CzechNameSubst {
        gender: CzechGender::PFem,
        allow: 7,
        choose: 1,
        name: "Luka",
    },
    CzechNameSubst {
        gender: CzechGender::PNeut,
        allow: 7,
        choose: 1,
        name: "Pole",
    },
];

pub(super) static NAME_CZECH_SUBST_STEM: &[CzechNameSubst] = &[
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 2,
        choose: 1,
        name: "Kostel",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 2,
        choose: 1,
        name: "Kl\u{00e1}\u{0161}ter",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 1,
        choose: 1,
        name: "Lhot",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 1,
        choose: 1,
        name: "Lhot",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 1,
        choose: 1,
        name: "Hur",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 6,
        choose: 0,
        name: "Sedl",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 7,
        choose: 1,
        name: "Hrad",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 2,
        choose: 0,
        name: "Pras",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 2,
        choose: 0,
        name: "Ba\u{017e}",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 2,
        choose: 0,
        name: "Tes",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 2,
        choose: 0,
        name: "U\u{017e}",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 6,
        choose: 2,
        name: "B\u{0159}",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 6,
        choose: 0,
        name: "Vod",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 6,
        choose: 0,
        name: "Jan",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Prach",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Kunr",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Strak",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "V\u{00ed}t",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Vy\u{0161}",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "\u{017d}at",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "\u{017d}er",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "St\u{0159}ed",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Harv",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Pruh",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Tach",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "P\u{00ed}sn",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Jin",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Jes",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Jar",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Sok",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Hod",
    },
    CzechNameSubst {
        gender: CzechGender::NFree,
        allow: 4,
        choose: 0,
        name: "Net",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 0,
        name: "Pra\u{017e}",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 0,
        name: "Nerat",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 0,
        name: "Kral",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 0,
        name: "Hut",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 4,
        name: "Pan",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 7,
        choose: 4,
        name: "Odst\u{0159}ed",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 7,
        choose: 1,
        name: "Mrat",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 4,
        choose: 1,
        name: "Hlav",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 3,
        choose: 0,
        name: "M\u{011b}\u{0159}",
    },
    CzechNameSubst {
        gender: CzechGender::Free,
        allow: 6,
        choose: 0,
        name: "Lip",
    },
];

pub(super) static NAME_CZECH_SUBST_ENDING: &[CzechNameSubst] = &[
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 3,
        choose: 7,
        name: "ec",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 3,
        choose: 7,
        name: "\u{00ed}n",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 7,
        choose: 7,
        name: "ov",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 5,
        choose: 7,
        name: "kov",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 4,
        choose: 2,
        name: "\u{00ed}n",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 4,
        choose: 2,
        name: "n\u{00ed}k",
    },
    CzechNameSubst {
        gender: CzechGender::SMasc,
        allow: 4,
        choose: 7,
        name: "burk",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 1,
        choose: 7,
        name: "ka",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 2,
        choose: 7,
        name: "inka",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 2,
        choose: 7,
        name: "n\u{00e1}",
    },
    CzechNameSubst {
        gender: CzechGender::SFem,
        allow: 4,
        choose: 7,
        name: "ava",
    },
    CzechNameSubst {
        gender: CzechGender::PMasc,
        allow: 4,
        choose: 2,
        name: "\u{00ed}ky",
    },
    CzechNameSubst {
        gender: CzechGender::PMasc,
        allow: 4,
        choose: 7,
        name: "upy",
    },
    CzechNameSubst {
        gender: CzechGender::PMasc,
        allow: 4,
        choose: 7,
        name: "olupy",
    },
    CzechNameSubst {
        gender: CzechGender::PFem,
        allow: 4,
        choose: 7,
        name: "avy",
    },
    CzechNameSubst {
        gender: CzechGender::PFem,
        allow: 7,
        choose: 7,
        name: "ice",
    },
    CzechNameSubst {
        gender: CzechGender::PFem,
        allow: 7,
        choose: 7,
        name: "i\u{010d}ky",
    },
    CzechNameSubst {
        gender: CzechGender::PNeut,
        allow: 3,
        choose: 7,
        name: "na",
    },
    CzechNameSubst {
        gender: CzechGender::SNeut,
        allow: 3,
        choose: 7,
        name: "no",
    },
    CzechNameSubst {
        gender: CzechGender::SNeut,
        allow: 4,
        choose: 7,
        name: "i\u{0161}t\u{011b}",
    },
];
