#!/usr/bin/env python3
"""Extrae catenaria Action5 (tipo 05) de ogfxe_extra a tiles/.

OpenGFX guarda wires/postes en Action5 del GRF *extra*, no en ogfx1_base
(IDs 1039–1074 del base son vía/depósito/plataforma). Este script:

  - rail_{1039..1062}.png          wires WSO 0..23
  - rail_catenary_entrance_{0..3}.png  WSO_ENTRANCE 24..27
  - rail_pylon_{0..7}.png          PSO 28..35

Busca NFO/sheets en:
  assets/opengfx/opengfx-*/sprites/ogfxe_extra*
  assets/opengfx/.signal-src-8bpp/sprites/ogfxe_extra*

En modo 32bpp, `descargar_graficos.sh` prepara `.signal-src-8bpp` porque
OpenGFX2 aún no ofrece este bloque Action5 elrail en 32bpp.
TODO(32bpp-nativo): preferir ogfx2e_extra_32ez cuando exista el bloque.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from PIL import Image

from opengfx_palette import dematte_legacy_colorkey, indexed_dos_to_rgba

ROOT = Path(__file__).resolve().parents[1]
TILES = ROOT / "assets" / "opengfx" / "tiles"
OUT_RS = ROOT / "crates" / "openttdrs-client" / "src" / "sprites" / "catenary_gfx_data_generated.rs"

A5_PAT = re.compile(r"\*\s*5\s+05\s+05\s+FF\s+30")
SPRITE_PAT = re.compile(
    r"^\s*(\d+)\s+(\S+)\s+(?:8bpp|32bpp)\s+"
    r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(-?\d+)\s+(-?\d+)"
)


def find_extra_nfo() -> Path | None:
    base = ROOT / "assets" / "opengfx"
    candidates = [
        *sorted(base.glob("opengfx-*/sprites/ogfxe_extra.nfo")),
        base / ".signal-src-8bpp" / "sprites" / "ogfxe_extra.nfo",
        base
        / ".signal-src-8bpp"
        / "extract"
        / "opengfx-8.0"
        / "sprites"
        / "ogfxe_extra.nfo",
    ]
    for p in candidates:
        if p.is_file():
            return p
    return None


def dematte_palette0(img: Image.Image) -> Image.Image:
    if img.mode == "P":
        return indexed_dos_to_rgba(img)
    return dematte_legacy_colorkey(img)


def load_sheet(sheet_dir: Path, name: str) -> Image.Image | None:
    for cand in (
        name,
        name.replace(".png", ".32.png"),
        Path(name).with_suffix(".pcx").name,
    ):
        p = sheet_dir / cand
        if p.is_file() and p.stat().st_size > 0:
            return dematte_palette0(Image.open(p))
    return None


def generated_metadata(sprites: list[tuple[str, ...]], nfo: Path) -> str:
    """Devuelve las anclas NFO de los 36 slots Action5 de catenaria.

    Los PNG se recortan a su rectángulo visible, pero OpenTTD los dibuja desde
    el origen de mundo más ``x_offs``/``y_offs``. Mantener ambos datos en la
    misma extracción evita que una actualización de OpenGFX conserve los
    píxeles correctos con un ancla equivocada.
    """
    lines = [
        "// @generated by scripts/extract_elrail_catenary.py — no editar a mano.",
        "// Fuente: bloque Action5 05/30 de OpenGFX ogfxe_extra.nfo.",
        f"// NFO: {nfo.relative_to(ROOT)}.",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq)]",
        "pub struct CatenarySpriteGfx {",
        "    pub width: f32,",
        "    pub height: f32,",
        "    pub x_offs: f32,",
        "    pub y_offs: f32,",
        "}",
        "",
        "/// Índice Action5: wires 0..23, entradas 24..27, postes 28..35.",
        "pub const CATENARY_ACTION5_GFX: [CatenarySpriteGfx; 36] = [",
    ]
    for slot, row in enumerate(sprites[:36]):
        width, height, x_offs, y_offs = (int(row[index]) for index in range(4, 8))
        lines.append(
            "    CatenarySpriteGfx { "
            f"width: {width}.0, height: {height}.0, "
            f"x_offs: {x_offs}.0, y_offs: {y_offs}.0 }}, // slot {slot}"
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main(*, check: bool = False) -> int:
    nfo = find_extra_nfo()
    if nfo is None:
        print("  (omitido elrail Action5: no hay ogfxe_extra.nfo)")
        return 0
    sheet_dir = nfo.parent
    lines = nfo.read_text(errors="replace").splitlines()
    start = next((i + 1 for i, l in enumerate(lines) if A5_PAT.search(l)), None)
    if start is None:
        print(f"  (omitido elrail Action5: sin bloque 05 05 en {nfo})")
        return 0
    sprites: list[tuple] = []
    for line in lines[start : start + 80]:
        m = SPRITE_PAT.match(line)
        if not m:
            if len(sprites) >= 48:
                break
            continue
        sprites.append(m.groups())
        if len(sprites) >= 48:
            break
    if len(sprites) < 36:
        print(f"  (omitido elrail Action5: solo {len(sprites)} sprites en {nfo})")
        return 0

    metadata = generated_metadata(sprites, nfo)
    if check:
        if not OUT_RS.is_file() or OUT_RS.read_text(encoding="utf-8") != metadata:
            print(
                "DRIFT elrail Action5: catenary_gfx_data_generated.rs no coincide; "
                "ejecutá scripts/extract_elrail_catenary.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK elrail Action5: metadata coincide ({OUT_RS.relative_to(ROOT)})")
        return 0

    OUT_RS.write_text(metadata, encoding="utf-8")

    TILES.mkdir(parents=True, exist_ok=True)
    sheets: dict[str, Image.Image] = {}
    written = 0
    for i, g in enumerate(sprites[:48]):
        sheet_name = Path(g[1]).name
        if sheet_name not in sheets:
            img = load_sheet(sheet_dir, sheet_name)
            if img is None:
                print(f"  (omitido elrail_{i:02d}: sheet {sheet_name})")
                continue
            sheets[sheet_name] = img
        x, y, w, h = map(int, g[2:6])
        crop = sheets[sheet_name].crop((x, y, x + w, y + h))
        if i < 24:
            out = TILES / f"rail_{1039 + i}.png"
        elif i < 28:
            out = TILES / f"rail_catenary_entrance_{i - 24}.png"
        elif i < 36:
            out = TILES / f"rail_pylon_{i - 28}.png"
        else:
            # GUI / extras Action5 — no usados por el cliente aún.
            continue
        crop.save(out)
        written += 1
    print(
        f"  elrail Action5: {written} tiles + metadata desde {nfo.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="verifica metadata sin escribir PNG ni Rust"
    )
    args = parser.parse_args()
    sys.exit(main(check=args.check))
