#!/usr/bin/env python3
"""Extrae los cuatro sprites vanilla de road waypoints.

Los postes de los waypoints viales no forman parte de ``ogfx1_base``: son el
pequeño bloque oficial ``road_waypoints.png`` que OpenTTD publica después del
sprite ficticio de paleta.  El extractor conserva los offsets NFO y genera la
tabla usada por el renderer, además de los recortes RGBA que consume el atlas.

La fuente opcional es el checkout de referencia de paridad.  Si no está
instalado, el script devuelve ``2`` (igual que los extractores de los demás
bloques de ``openttd.grf``) y deja intactos los assets ya generados.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from PIL import Image

from opengfx_palette import dematte_legacy_colorkey, indexed_dos_to_rgba

ROOT = Path(__file__).resolve().parents[1]
TILES = ROOT / "assets" / "opengfx" / "tiles"
OUT_RS = ROOT / "crates" / "openttdrs-client" / "src" / "sprites" / "road_waypoint_gfx_data_generated.rs"

SPRITE_IDS = (6141, 6142, 6143, 6144)  # Y_W, Y_E, X_W, X_E
SPRITE_NAMES = ("road_waypoint_y_w", "road_waypoint_y_e", "road_waypoint_x_w", "road_waypoint_x_e")

ROW = re.compile(
    r"^\s*-?\d+\s+(\S+)\s+8bpp\s+"
    r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(-?\d+)\s+(-?\d+)"
)

def find_nfo() -> Path | None:
    candidates = (
        ROOT / "reference" / "openttd-15.3-oracle" / "media" / "baseset" / "openttd" / "road_waypoints.nfo",
        ROOT / "reference" / "openttd-upstream" / "media" / "baseset" / "openttd" / "road_waypoints.nfo",
        ROOT / "assets" / "openttd" / "road_waypoints.nfo",
    )
    return next((path for path in candidates if path.is_file()), None)


def find_sheet(nfo: Path, name: str) -> Path | None:
    relative = Path(name)
    candidates = (
        nfo.parent / relative,
        ROOT / "reference" / "openttd-15.3-oracle" / "build" / "media" / "baseset" / "openttd" / relative,
        ROOT / "reference" / "openttd-upstream" / "build" / "media" / "baseset" / "openttd" / relative,
        ROOT / "assets" / "openttd" / relative,
    )
    return next((path for path in candidates if path.is_file()), None)


def parse_rows(nfo: Path) -> list[tuple[str, int, int, int, int, int, int]]:
    rows = []
    for line in nfo.read_text(encoding="utf-8", errors="replace").splitlines():
        match = ROW.match(line)
        if match is None:
            continue
        rows.append(
            (
                match.group(1),
                *(int(match.group(index)) for index in range(2, 8)),
            )
        )
    return rows


def generated_metadata(rows: list[tuple[str, int, int, int, int, int, int]], nfo: Path) -> str:
    if len(rows) != 4:
        raise ValueError(f"se esperaban 4 filas NFO de road waypoint, hay {len(rows)}")
    lines = [
        "// @generated by scripts/extract_road_waypoint_sprites.py — no editar a mano.",
        f"// Fuente: {nfo.relative_to(ROOT)}.",
        "",
        "/// IDs globales `SPR_ROAD_WAYPOINT_*` del GRF oficial.",
        "#[allow(dead_code)]",
        "pub const ROAD_WAYPOINT_SPRITE_IDS: [u32; 4] = [6141, 6142, 6143, 6144];",
        "#[allow(dead_code)]",
        "pub const ROAD_WAYPOINT_SPRITE_PATHS: [&str; 4] = [",
    ]
    for name in SPRITE_NAMES:
        lines.append(f'    "assets/opengfx/tiles/{name}.png",')
    lines.extend(
        [
            "];",
            "",
            "#[allow(dead_code)]",
            "pub const ROAD_WAYPOINT_SPRITE_META: [(u32, f32, f32, f32, f32); 4] = [",
        ]
    )
    for sprite_id, row in zip(SPRITE_IDS, rows, strict=True):
        _sheet, _x, _y, width, height, x_offs, y_offs = row
        lines.append(
            f"    ({sprite_id}, {width}.0, {height}.0, {x_offs}.0, {y_offs}.0),"
        )
    lines.append("];\n")

    # Dos entradas por eje: OpenTTD las consume como dos líneas BUILD y las
    # ordena con los mismos bounds que las paradas drive-through.
    lines.extend(
        [
            "",
            "pub const ROAD_WAYPOINT_BUILD_LAYERS: [[RoadStopLayerGfx; 2]; 2] = [",
            "    [",
            "        RoadStopLayerGfx {",
            "            sprite_id: 6143, bounds: (16, 3, 16), dx: 0.0, dy: 0.0, dz: 0.0,",
            "            z: 0.05, w: 64.0, h: 35.0, x_offs: -31.0, y_offs: -4.0, remap_x_adj: 0.0,",
            '            path: "assets/opengfx/tiles/road_waypoint_x_w.png",',
            "        },",
            "        RoadStopLayerGfx {",
            "            sprite_id: 6144, bounds: (16, 3, 16), dx: 0.0, dy: 13.0, dz: 0.0,",
            "            z: 0.06, w: 64.0, h: 35.0, x_offs: -57.0, y_offs: -17.0, remap_x_adj: 0.0,",
            '            path: "assets/opengfx/tiles/road_waypoint_x_e.png",',
            "        },",
            "    ],",
            "    [",
            "        RoadStopLayerGfx {",
            "            sprite_id: 6141, bounds: (3, 16, 16), dx: 13.0, dy: 0.0, dz: 0.0,",
            "            z: 0.05, w: 64.0, h: 40.0, x_offs: -5.0, y_offs: -22.0, remap_x_adj: 0.0,",
            '            path: "assets/opengfx/tiles/road_waypoint_y_w.png",',
            "        },",
            "        RoadStopLayerGfx {",
            "            sprite_id: 6142, bounds: (3, 16, 16), dx: 0.0, dy: 0.0, dz: 0.0,",
            "            z: 0.06, w: 64.0, h: 40.0, x_offs: -31.0, y_offs: -9.0, remap_x_adj: 0.0,",
            '            path: "assets/opengfx/tiles/road_waypoint_y_e.png",',
            "        },",
            "    ],",
            "];",
            "",
        ]
    )
    return "\n".join(lines)


def main(*, check: bool = False) -> int:
    nfo = find_nfo()
    if nfo is None:
        print("  (omitido road waypoint vanilla: no hay road_waypoints.nfo local)")
        return 2
    rows = parse_rows(nfo)
    if len(rows) != 4:
        print(f"  (omitido road waypoint vanilla: filas NFO encontradas={len(rows)})", file=sys.stderr)
        return 2
    metadata = generated_metadata(rows, nfo)
    if check:
        if not OUT_RS.is_file() or OUT_RS.read_text(encoding="utf-8") != metadata:
            print(
                "DRIFT road waypoint vanilla: road_waypoint_gfx_data_generated.rs no coincide; "
                "ejecutá scripts/extract_road_waypoint_sprites.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK road waypoint vanilla: metadata coincide ({OUT_RS.relative_to(ROOT)})")
        return 0

    TILES.mkdir(parents=True, exist_ok=True)
    written = 0
    for row, name in zip(rows, SPRITE_NAMES, strict=True):
        sheet = find_sheet(nfo, row[0])
        if sheet is None:
            print(f"  (omitido {name}: falta hoja {row[0]})", file=sys.stderr)
            continue
        _sheet, x, y, width, height, _x_offs, _y_offs = row
        with Image.open(sheet) as image:
            rgba = dematte_legacy_colorkey(indexed_dos_to_rgba(image))
            crop = rgba.crop((x, y, x + width, y + height))
        crop.save(TILES / f"{name}.png")
        written += 1
    OUT_RS.write_text(metadata, encoding="utf-8")
    print(f"  road waypoint vanilla: {written} sprites + metadata desde {nfo.relative_to(ROOT)}")
    return 0 if written == 4 else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verifica metadata sin escribir PNG ni Rust")
    args = parser.parse_args()
    raise SystemExit(main(check=args.check))
