#!/usr/bin/env python3
"""Extrae el bloque vanilla de tranvías del GRF ``openttd``.

Los sprites de tranvía no pertenecen a ``ogfx1_base`` ni a
``ogfxe_extra``: OpenTTD los publica mediante Action5 ``0x0B`` desde el GRF
base ``openttd``.  El proyecto sólo necesita el recorte 8bpp para el atlas,
pero hasta ahora ``descargar_graficos.sh`` copiaba los sprites de carretera
cuando no encontraba esos IDs.  Eso hacía que el overlay del tranvía y la
catenaria vial fueran visualmente imposibles de distinguir del asfalto.

El extractor usa el NFO generado por ``grfcodec`` y conserva los offsets NFO
en una tabla Rust generada.  Busca primero el checkout de referencia que usan
los scripts de paridad y también acepta un GRF ``openttd`` instalado dentro de
``assets/``.  Si no hay fuente local, devuelve ``2`` para que los pipelines
que descargan assets puedan omitirlo sin fallar.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from PIL import Image

from opengfx_palette import indexed_dos_to_rgba

ROOT = Path(__file__).resolve().parents[1]
TILES = ROOT / "assets" / "opengfx" / "tiles"
OUT_RS = ROOT / "crates" / "openttdrs-client" / "src" / "sprites" / "tramway_catenary_gfx_data_generated.rs"

FIRST_SPRITE = 1261
SPRITE_COUNT = 119
LAST_SPRITE = FIRST_SPRITE + SPRITE_COUNT - 1

ROW = re.compile(
    r"^\s*(\d+)\s+(\S+)\s+8bpp\s+"
    r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(-?\d+)\s+(-?\d+)"
)


def find_nfo() -> Path | None:
    candidates = [
        ROOT / "reference" / "openttd-15.3-oracle" / "build" / "media" / "baseset" / "openttd" / "sprites" / "openttd.nfo",
        ROOT / "reference" / "openttd-upstream" / "build" / "media" / "baseset" / "openttd" / "sprites" / "openttd.nfo",
        ROOT / "assets" / "openttd" / "sprites" / "openttd.nfo",
    ]
    return next((path for path in candidates if path.is_file()), None)


def parse_rows(nfo: Path) -> dict[int, tuple[str, int, int, int, int, int, int]]:
    rows: dict[int, tuple[str, int, int, int, int, int, int]] = {}
    for line in nfo.read_text(encoding="utf-8", errors="replace").splitlines():
        match = ROW.match(line)
        if match is None:
            continue
        sprite_id = int(match.group(1))
        if not FIRST_SPRITE <= sprite_id <= LAST_SPRITE:
            continue
        rows[sprite_id] = (
            Path(match.group(2)).name,
            *(int(match.group(i)) for i in range(3, 9)),
        )
    return rows


def generated_metadata(rows: dict[int, tuple[str, int, int, int, int, int, int]], nfo: Path) -> str:
    lines = [
        "// @generated by scripts/extract_tramway_sprites.py — no editar a mano.",
        "// Fuente: bloque Action5 0x0B del GRF openttd.nfo.",
        f"// NFO: {nfo.relative_to(ROOT)}.",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq)]",
        "pub struct TramwaySpriteGfx {",
        "    pub width: f32,",
        "    pub height: f32,",
        "    pub x_offs: f32,",
        "    pub y_offs: f32,",
        "}",
        "",
        "/// 119 offsets de `SPR_TRAMWAY_BASE`, incluyendo overlay, catenaria, túnel y puente.",
        "pub const TRAMWAY_SPRITE_GFX: [TramwaySpriteGfx; 119] = [",
    ]
    for offset in range(SPRITE_COUNT):
        _sheet, _x, _y, width, height, x_offs, y_offs = rows[FIRST_SPRITE + offset]
        lines.append(
            "    TramwaySpriteGfx { "
            f"width: {width}.0, height: {height}.0, "
            f"x_offs: {x_offs}.0, y_offs: {y_offs}.0 }}, // offset {offset}"
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main(*, check: bool = False) -> int:
    nfo = find_nfo()
    if nfo is None:
        print("  (omitido tranvía vanilla: no hay openttd.nfo local)")
        return 2
    rows = parse_rows(nfo)
    missing = [sprite_id for sprite_id in range(FIRST_SPRITE, LAST_SPRITE + 1) if sprite_id not in rows]
    if missing:
        print(f"  (omitido tranvía vanilla: faltan filas NFO {missing[:4]}…)", file=sys.stderr)
        return 2

    metadata = generated_metadata(rows, nfo)
    if check:
        if not OUT_RS.is_file() or OUT_RS.read_text(encoding="utf-8") != metadata:
            print(
                "DRIFT tranvía vanilla: tramway_catenary_gfx_data_generated.rs no coincide; "
                "ejecutá scripts/extract_tramway_sprites.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK tranvía vanilla: metadata coincide ({OUT_RS.relative_to(ROOT)})")
        return 0

    TILES.mkdir(parents=True, exist_ok=True)
    sheets: dict[str, Image.Image] = {}
    written = 0
    for offset in range(SPRITE_COUNT):
        sheet_name, x, y, width, height, _x_offs, _y_offs = rows[FIRST_SPRITE + offset]
        if sheet_name not in sheets:
            sheet_path = nfo.parent / sheet_name
            if not sheet_path.is_file():
                print(f"  (omitido tramway_{offset:03d}: falta {sheet_path})", file=sys.stderr)
                continue
            sheets[sheet_name] = indexed_dos_to_rgba(Image.open(sheet_path))
        crop = sheets[sheet_name].crop((x, y, x + width, y + height))
        crop.save(TILES / f"tramway_{offset:03d}.png")
        # Mantener los nombres públicos que ya consumen los previews y el
        # renderer.  Ahora contienen el overlay real, no una copia de road.
        if 4 <= offset < 23:
            crop.save(TILES / f"tram_flat_{offset - 4:02d}.png")
        written += 1

    OUT_RS.write_text(metadata, encoding="utf-8")
    print(f"  tranvía vanilla: {written} sprites + metadata desde {nfo.relative_to(ROOT)}")
    return 0 if written == SPRITE_COUNT else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verifica metadata sin escribir PNG ni Rust")
    args = parser.parse_args()
    raise SystemExit(main(check=args.check))
