#!/usr/bin/env python3
"""Genera INDUSTRY_GFX_DATA para openttdrs desde OpenTTD src/table/industry_land.h.

Usa la fila del estadio 3 por gfx (índice gfx*4+3), igual que GetIndustryGfx completado.
s1 = suelo (temperate grass 0xF54 -> no duplicar como PNG extra).
s2 = edificio (0 = sin overlay).

Offsets w/h/xrel/yrel: PNG `assets/opengfx/tiles/industry_<id>.png` si existe;
si no, extensión sx/sy del macro M() en unidades de 16px (OpenTTD).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore[misc, assignment]

GRASS_S1 = 0xF54
# Calibración manual (tiles mina de carbón, validados en cliente).
CAL: dict[int, tuple[float, float, float, float]] = {
    0: (58.0, 50.0, -16.0, -33.0),
    1: (46.0, 53.0, -14.0, -38.0),
    2: (64.0, 39.0, -31.0, -8.0),
    3: (44.0, 38.0, -13.0, -21.0),
}
# Factores derivados de gfx 0 (mina) para auto-calibrar otros PNG.
XREL_PER_W = -16.0 / 58.0
YREL_PER_H = -33.0 / 50.0
FALLBACK = (64.0, 48.0, -32.0, -32.0)


def parse_atom(a: str) -> int:
    a = a.split("|")[0].strip()
    return int(a, 16) if a.startswith("0x") else int(a)


def parse_macro_rows(path: Path) -> list[tuple[int, int, int, int, int, int]]:
    """s1, s2, dx, dy, sx, sy por cada fila M()."""
    pat = re.compile(
        r"^\s*M\(\s*([^,]+),\s*PAL_NONE,\s*([^,]+),\s*PAL_NONE,\s*"
        r"(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),"
    )
    out: list[tuple[int, int, int, int, int, int]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = pat.match(line)
        if not m:
            continue
        try:
            out.append(
                (
                    parse_atom(m.group(1)),
                    parse_atom(m.group(2)),
                    int(m.group(3)),
                    int(m.group(4)),
                    int(m.group(5)),
                    int(m.group(6)),
                )
            )
        except ValueError:
            continue
    return out


def png_size(tiles_dir: Path, sid: int) -> tuple[int, int] | None:
    if sid == 0 or Image is None:
        return None
    p = tiles_dir / f"industry_{sid}.png"
    if not p.is_file():
        return None
    with Image.open(p) as im:
        return im.size


def overlay_from_png(
    tiles_dir: Path, sprite_id: int, ground_id: int, dx: int, dy: int, sx: int, sy: int
) -> tuple[float, float, float, float]:
    """w, h, xrel, yrel para overlay de edificio o solo suelo."""
    bld = png_size(tiles_dir, sprite_id)
    gnd = png_size(tiles_dir, ground_id)
    if bld:
        w, h = float(bld[0]), float(bld[1])
        xrel = w * XREL_PER_W + float(dx) * 2.0
        yrel = h * YREL_PER_H + float(dy) * 2.0
        return (w, h, xrel, yrel)
    if gnd:
        w, h = float(gnd[0]), float(gnd[1])
        xrel = w * XREL_PER_W + float(dx) * 2.0
        yrel = h * YREL_PER_H + float(dy) * 2.0
        return (w, h, xrel, yrel)
    w = max(float(sx) * 8.0, 32.0)
    h = max(float(sy) * 8.0, 24.0)
    xrel = float(dx) * 8.0 - w * 0.5 + 8.0
    yrel = float(dy) * 8.0 - h + 12.0
    return (w, h, xrel, yrel)


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    upstream = repo / "third_party" / "openttd" / "industry_land.h"
    if len(sys.argv) >= 2:
        upstream = Path(sys.argv[1])
    if not upstream.is_file():
        print(
            f"Falta {upstream}. Copiá industry_land.h desde OpenTTD o pasá ruta como argv[1].",
            file=sys.stderr,
        )
        return 1

    rows_macro = parse_macro_rows(upstream)
    need = 120 * 4
    if len(rows_macro) < need:
        print(f"Entries insuficientes: {len(rows_macro)} < {need}", file=sys.stderr)
        return 1

    tiles_dir = repo / "assets" / "opengfx" / "tiles"
    out_path = (
        repo / "crates" / "openttdrs-client" / "src" / "sprites" / "industry_gfx_data_generated.rs"
    )

    body_rows: list[str] = []
    png_cal = 0
    macro_cal = 0
    fallback_cal = 0
    for gfx in range(120):
        idx = gfx * 4 + 3
        s1, s2, dx, dy, sx, sy = rows_macro[idx]
        gid = 0 if s1 == GRASS_S1 else s1
        if gfx in CAL:
            w, h, xr, yr = CAL[gfx]
        else:
            dims = overlay_from_png(tiles_dir, s2, gid, dx, dy, sx, sy)
            if png_size(tiles_dir, s2) or (gid and png_size(tiles_dir, gid)):
                png_cal += 1
                w, h, xr, yr = dims
            elif s2 != 0 or gid != 0:
                macro_cal += 1
                w, h, xr, yr = dims
            else:
                fallback_cal += 1
                w, h, xr, yr = FALLBACK
        body_rows.append(
            f"    IndustryGfxSprite {{ sprite_id: {s2}, ground_sprite_id: {gid}, "
            f"w: {w:.1f}, h: {h:.1f}, xrel: {xr:.1f}, yrel: {yr:.1f} }},"
        )

    lines = [
        "// @generated by scripts/gen_industry_gfx_data.py — no editar a mano.",
        "// Fuente: OpenTTD _industry_draw_tile_data, estadio 3 por gfx (gfx*4+3).",
        "// Offsets: PNG industry_<id>.png o macro M(dx,dy,sx,sy).",
        "",
        f"pub const INDUSTRY_GFX_DATA: [IndustryGfxSprite; 120] = [\n"
        + "\n".join(body_rows)
        + "\n];",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Escrito {out_path} (png={png_cal} macro={macro_cal} fallback={fallback_cal})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
