#!/usr/bin/env python3
"""Genera `industry_anim_state_generated.rs` desde OpenTTD `table/build_industry.h`.

Cada fila `MT(..., anim_state)` define si el subíndice de `_industry_draw_tile_data`
usa `m4 & 3` (animación) o la etapa de obra (`m1`).
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

GFX_COUNT = 131
BUILD_INDUSTRY_URL = (
    "https://raw.githubusercontent.com/OpenTTD/OpenTTD/master/src/table/build_industry.h"
)


def fetch_build_industry() -> str:
    vendored = Path(__file__).resolve().parents[1] / "third_party/openttd/build_industry.h"
    if vendored.is_file():
        return vendored.read_text(encoding="utf-8")
    try:
        with urllib.request.urlopen(BUILD_INDUSTRY_URL, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except OSError as e:
        raise SystemExit(f"No se pudo leer build_industry.h ({e})") from e


def parse_anim_state(text: str) -> list[bool]:
    pat = re.compile(r"^\tMT\([^)]+\)", re.M)
    rows: list[bool] = []
    for line in pat.findall(text):
        m = re.search(r",\s*(true|false)\s*\)\s*,?\s*$", line)
        if not m:
            raise SystemExit(f"MT sin anim_state: {line[:80]}")
        rows.append(m.group(1) == "true")
    if len(rows) < GFX_COUNT:
        raise SystemExit(f"Esperadas >={GFX_COUNT} filas MT, got {len(rows)}")
    return rows[:GFX_COUNT]


def emit(flags: list[bool], out: Path) -> None:
    true_gfx = [i for i, v in enumerate(flags) if v]
    lines = [
        "// @generated by scripts/gen_industry_anim_state.py — no editar a mano.",
        f"// gfx con anim_state=true ({len(true_gfx)}): {true_gfx}",
        "",
        "/// `IndustryTileSpec.anim_state` por gfx (OpenTTD `build_industry.h` MT macro).",
        f"pub const INDUSTRY_TILE_ANIM_STATE: [bool; {GFX_COUNT}] = [",
    ]
    for i in range(0, GFX_COUNT, 8):
        chunk = flags[i : i + 8]
        lines.append(
            "    "
            + ", ".join("true" if v else "false" for v in chunk)
            + ","
        )
    lines.append("];")
    lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    out = (
        repo
        / "crates/openttdrs-client/src/sprites/industry_anim_state_generated.rs"
    )
    flags = parse_anim_state(fetch_build_industry())
    emit(flags, out)
    print(f"Wrote {out} ({sum(flags)} anim_state tiles)")


if __name__ == "__main__":
    main()
