#!/usr/bin/env python3
"""Genera vehicle_gfx_data_generated.rs desde sprites OpenGFX (bus + camión MPS).

OpenTTD `roadveh_cmd.cpp`: `sprite = direction + _roadveh_images[spritenum]`.
Índice 0..7 = `Direction` (`N`, `NE`, `E`, `SE`, `S`, `SW`, `W`, `NW`).
"""
from __future__ import annotations

import sys
from pathlib import Path

from nfo_sprite_meta import detect_graphics_mode, parse_sprite_offs, sprite_dims_from_assets

# OpenTTD Direction 0..7
DIR_NAMES = ("n", "ne", "e", "se", "s", "sw", "w", "nw")
FALLBACK = (20.0, 16.0, -14.0, -7.0)

GFX_SETS: tuple[tuple[str, tuple[tuple[int, str], ...]], ...] = (
    (
        "BUS_VEHICLE_LAYERS",
        (
            (3092, "vehicle_bus_n.png"),
            (3093, "vehicle_bus_ne.png"),
            (3094, "vehicle_bus_e.png"),
            (3095, "vehicle_bus_se.png"),
            (3096, "vehicle_bus_s.png"),
            (3097, "vehicle_bus_sw.png"),
            (3098, "vehicle_bus_w.png"),
            (3099, "vehicle_bus_nw.png"),
        ),
    ),
    (
        "TRUCK_VEHICLE_LAYERS",
        (
            (3100, "vehicle_truck_n.png"),
            (3101, "vehicle_truck_ne.png"),
            (3102, "vehicle_truck_e.png"),
            (3103, "vehicle_truck_se.png"),
            (3104, "vehicle_truck_s.png"),
            (3105, "vehicle_truck_sw.png"),
            (3106, "vehicle_truck_w.png"),
            (3107, "vehicle_truck_nw.png"),
        ),
    ),
    (
        "TRUCK_VEHICLE_LAYERS_LOADED",
        (
            (3188, "vehicle_truck_n_loaded.png"),
            (3189, "vehicle_truck_ne_loaded.png"),
            (3190, "vehicle_truck_e_loaded.png"),
            (3191, "vehicle_truck_se_loaded.png"),
            (3192, "vehicle_truck_s_loaded.png"),
            (3193, "vehicle_truck_sw_loaded.png"),
            (3194, "vehicle_truck_w_loaded.png"),
            (3195, "vehicle_truck_nw_loaded.png"),
        ),
    ),
)


def emit_layers(
    repo: Path,
    tiles_dir: Path,
    nfo: dict,
    prefer_bpp: str | None,
    set_name: str,
    entries: tuple[tuple[int, str], ...],
) -> tuple[list[str], list[str], int]:
    rows: list[str] = []
    missing: list[str] = []
    nfo_ok = 0
    rows.append(f"pub const {set_name}: [VehicleLayerGfx; 8] = [")
    for (dir_name, (sid, png)) in zip(DIR_NAMES, entries, strict=True):
        w, h, xr, yr, note = sprite_dims_from_assets(
            repo,
            tiles_dir,
            nfo,
            sid,
            png,
            prefer_bpp,
            fallback=FALLBACK,
        )
        if note.startswith("nfo"):
            nfo_ok += 1
        if not (tiles_dir / png).is_file():
            missing.append(png)
        rows.append(f"    // {dir_name.upper()} (sprite {sid})")
        rows.append(
            f"    VehicleLayerGfx {{ w: {w:.1f}, h: {h:.1f}, "
            f"x_offs: {xr:.1f}, y_offs: {yr:.1f}, "
            f'path: "assets/opengfx/tiles/{png}" }},'
        )
    rows.append("];")
    rows.append("")
    return rows, missing, nfo_ok


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    tiles_dir = repo / "assets" / "opengfx" / "tiles"
    out_path = (
        repo / "crates" / "openttdrs-client" / "src" / "sprites" / "vehicle_gfx_data_generated.rs"
    )
    nfo = parse_sprite_offs(repo)
    prefer_bpp = detect_graphics_mode(repo)

    lines = [
        "// @generated by scripts/gen_vehicle_gfx_data.py — no editar a mano.",
        "// Fuente: OpenGFX bus/camión MPS — 8 direcciones OpenTTD (sprites 3092..3099 / 3100..3107).",
        f"// Modo gráfico detectado: {prefer_bpp or 'desconocido'}.",
        "",
        "#[derive(Debug, Clone, Copy)]",
        "pub struct VehicleLayerGfx {",
        "    pub w: f32,",
        "    pub h: f32,",
        "    pub x_offs: f32,",
        "    pub y_offs: f32,",
        "    pub path: &'static str,",
        "}",
        "",
        "/// Índice = `Vehicle::render_direction()` (`OpenTTD` `Direction` 0..7).",
    ]

    all_missing: list[str] = []
    total_nfo = 0
    for set_name, entries in GFX_SETS:
        block, missing, nfo_ok = emit_layers(
            repo, tiles_dir, nfo, prefer_bpp, set_name, entries
        )
        lines.extend(block)
        all_missing.extend(missing)
        total_nfo += nfo_ok

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Escrito {out_path} (nfo={total_nfo}/{8 * len(GFX_SETS)})")
    if all_missing:
        print(f"PNG ausentes: {all_missing}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
