#!/usr/bin/env python3
"""Genera INDUSTRY_GFX_DATA para openttdrs desde OpenTTD src/table/industry_land.h.

Usa la fila del estadio 3 por gfx (índice gfx*4+3), igual que GetIndustryGfx completado.
s1 = suelo (temperate grass 0xF54 -> no duplicar como PNG extra).
s2 = edificio (0 = sin overlay).
Salida: crates/openttdrs-client/src/sprites/industry_gfx_data_generated.rs
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

GRASS_S1 = 0xF54

# Calibración manual conservada (primeros tiles de mina de carbón).
CAL = {
    0: (58.0, 50.0, -16.0, -33.0),
    1: (46.0, 53.0, -14.0, -38.0),
    2: (64.0, 39.0, -31.0, -8.0),
    3: (44.0, 38.0, -13.0, -21.0),
}


def parse_atoms(path: Path) -> list[tuple[int, int]]:
    text = path.read_text(encoding="utf-8")

    def parse_atom(a: str) -> int:
        a = a.split("|")[0].strip()
        return int(a, 16) if a.startswith("0x") else int(a)

    pat = re.compile(r"^\s*M\(\s*([^,]+),\s*PAL_NONE,\s*([^,]+),")
    out: list[tuple[int, int]] = []
    for line in text.splitlines():
        m = pat.match(line)
        if not m:
            continue
        try:
            s1 = parse_atom(m.group(1).strip())
            s2 = parse_atom(m.group(2).strip())
            out.append((s1, s2))
        except ValueError:
            continue
    return out


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    upstream = repo / "third_party" / "openttd" / "industry_land.h"
    if len(sys.argv) >= 2:
        upstream = Path(sys.argv[1])
    if not upstream.is_file():
        print(
            f"Falta {upstream}. Copiá industry_land.h desde OpenTTD o pasá ruta como argv[1].",
            file=sys.stderr,
        )
        return 1

    entries = parse_atoms(upstream)
    need = 120 * 4
    if len(entries) < need:
        print(f"Entries insuficientes: {len(entries)} < {need}", file=sys.stderr)
        return 1

    out_path = repo / "crates" / "openttdrs-client" / "src" / "sprites" / "industry_gfx_data_generated.rs"
    lines: list[str] = [
        "// @generated by scripts/gen_industry_gfx_data.py — no editar a mano.",
        "// Fuente: OpenTTD _industry_draw_tile_data, estadio 3 por gfx (gfx*4+3).",
        "",
    ]

    rows: list[str] = []
    for gfx in range(120):
        idx = gfx * 4 + 3
        s1, s2 = entries[idx]
        gid = 0 if s1 == GRASS_S1 else s1
        if gfx in CAL:
            w, h, xr, yr = CAL[gfx]
            rows.append(
                f"    IndustryGfxSprite {{ sprite_id: {s2}, ground_sprite_id: {gid}, "
                f"w: {w}, h: {h}, xrel: {xr}, yrel: {yr} }},"
            )
        else:
            rows.append(
                f"    IndustryGfxSprite {{ sprite_id: {s2}, ground_sprite_id: {gid}, "
                f"w: 64.0, h: 48.0, xrel: -32.0, yrel: -32.0 }},"
            )

    body = "\n".join(rows)
    lines.append(f"pub const INDUSTRY_GFX_DATA: [IndustryGfxSprite; 120] = [\n{body}\n];")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Escrito {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
