#!/usr/bin/env python3
"""Genera road_depot_gfx_data_generated.rs desde OpenTTD road_land.h + PNG/NFO."""
from __future__ import annotations

import re
import sys
from pathlib import Path

from nfo_sprite_meta import (
    detect_graphics_mode,
    parse_sprite_offs,
    pick_sprite_meta,
    png_size,
)

DIRS = ("ne", "se", "sw", "nw")


def parse_depot_blocks(path: Path) -> dict[str, list[tuple[int, int, int, int, int, int]]]:
    text = path.read_text(encoding="utf-8")
    block_pat = re.compile(
        r"static const DrawTileSeqStruct _road_depot_(NE|SE|SW|NW)\[\] = \{([^}]+)\}",
        re.DOTALL,
    )
    line_pat = re.compile(
        r"TILE_SEQ_LINE\(\s*0x([0-9A-Fa-f]+)[^,]*,\s*[^,]+,\s*"
        r"(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+)"
    )
    out: dict[str, list[tuple[int, int, int, int, int, int]]] = {}
    for m in block_pat.finditer(text):
        name = m.group(1).lower()
        lines = []
        for img_hex, dx, dy, sx, sy in line_pat.findall(m.group(2)):
            sid = int(img_hex, 16) & 0x0FFF
            lines.append((sid, int(dx), int(dy), 0, int(sx), int(sy)))
        if lines:
            out[name] = lines
    return out


def sprite_png_name(sid: int) -> str:
    if 1408 <= sid <= 1411:
        return f"road_depot_{sid - 1408}.png"
    return f"rail_{sid}.png"


def compute_depot_layer_corrections(
    dx: float,
    dy: float,
    *,
    dir_i: int,
    layer_i: int,
) -> tuple[float, float]:
    """(remap_x_adj, y_offs_delta). Calibración fina SP3 checklist y=6."""
    # Boca 12×12 en esquina: mismos patrones que paradas bus en esquina opuesta.
    if dir_i == 1 and layer_i == 0 and dx == 0.0 and dy == 0.0:
        return -3.0, 0.0
    if dir_i == 2 and layer_i == 0 and dx == 0.0 and dy == 0.0:
        return -8.0, -4.0
    if dir_i == 1 and layer_i == 1 and dx == 15.0 and dy == 0.0:
        return 5.0, -6.0
    if dir_i == 2 and layer_i == 1 and dx == 0.0 and dy == 15.0:
        return -7.0, -6.0
    if dir_i == 3 and layer_i == 0 and dx == 15.0 and dy == 0.0:
        return 8.0, -6.0
    if dir_i == 0 and layer_i == 0 and dx == 0.0 and dy == 15.0:
        return -13.0, 0.0
    return 0.0, 0.0


def write_layers(
    blocks: dict[str, list[tuple[int, int, int, int, int, int]]],
    tiles_dir: Path,
    nfo: dict,
    prefer_bpp: str | None,
) -> list[str]:
    lines: list[str] = []
    for dir_i, dir_name in enumerate(DIRS):
        seq = blocks.get(dir_name, [])
        layer_lines: list[str] = []
        for layer_i, (sid, dx, dy, dz, sx, sy) in enumerate(seq):
            png = sprite_png_name(sid)
            wh = png_size(tiles_dir, png)
            w, h, xo, yo, _note = pick_sprite_meta(nfo.get(sid, []), wh, prefer_bpp)
            if w <= 0.0 or h <= 0.0:
                w, h = (float(sx * 2), float(sy * 2)) if wh is None else (float(wh[0]), float(wh[1]))
            adj, yo_delta = compute_depot_layer_corrections(
                float(dx), float(dy), dir_i=dir_i, layer_i=layer_i
            )
            yo += yo_delta
            z = 0.05 + layer_i * 0.01
            layer_lines.append(
                f"        RoadDepotLayerGfx {{ dx: {dx}.0, dy: {dy}.0, dz: {dz}.0, "
                f"z: {z:.2f}, w: {w:.1f}, h: {h:.1f}, x_offs: {xo:.1f}, y_offs: {yo:.1f}, "
                f"remap_x_adj: {adj:.1f}, "
                f'path: "assets/opengfx/tiles/{png}" }},'
            )
        lines.append(f"    &[ // {dir_name.upper()}")
        lines.extend(layer_lines or ["        // sin capas"])
        lines.append("    ],")
    return lines


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    upstream = repo / "third_party" / "openttd" / "road_land.h"
    if len(sys.argv) >= 2:
        upstream = Path(sys.argv[1])
    if not upstream.is_file():
        print(f"Falta {upstream}", file=sys.stderr)
        return 1

    blocks = parse_depot_blocks(upstream)
    tiles_dir = repo / "assets" / "opengfx" / "tiles"
    nfo = parse_sprite_offs(repo)
    prefer_bpp = detect_graphics_mode(repo)

    ground_png = "road_depot_ground.png"
    if not (tiles_dir / ground_png).is_file():
        ground_png = "airport_apron.png"

    mode_comment = (
        f"// Modo gráfico detectado: {prefer_bpp}.\n" if prefer_bpp else "// Modo gráfico: auto.\n"
    )
    out_path = (
        repo / "crates" / "openttdrs-client" / "src" / "sprites" / "road_depot_gfx_data_generated.rs"
    )
    layer_rows = write_layers(blocks, tiles_dir, nfo, prefer_bpp)
    lines = [
        "// @generated by scripts/gen_road_depot_gfx_data.py — no editar a mano.",
        "// Fuente: OpenTTD road_land.h (_road_depot_NE..NW) + PNG/NFO.",
        mode_comment,
        "",
        "#[derive(Debug, Clone, Copy)]",
        "pub struct RoadDepotLayerGfx {",
        "    pub dx: f32,",
        "    pub dy: f32,",
        "    pub dz: f32,",
        "    pub z: f32,",
        "    pub w: f32,",
        "    pub h: f32,",
        "    pub x_offs: f32,",
        "    pub y_offs: f32,",
        "    pub remap_x_adj: f32,",
        "    pub path: &'static str,",
        "}",
        "",
        f'pub const ROAD_DEPOT_GROUND_PATH: &str = "assets/opengfx/tiles/{ground_png}";',
        "",
        "pub const ROAD_DEPOT_BUILD_LAYERS: [&[RoadDepotLayerGfx]; 4] = [",
        *layer_rows,
        "];",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Escrito {out_path} ({sum(len(v) for v in blocks.values())} capas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
